### ISSUE TITLE
UX name unknown-target might be misleading

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#103]
When we are not using target groups and just use ad-hoc queries `Recent Jobs` section show output like this:
<img width="482" alt="zrzut ekranu 2018-12-27 o 10 37 32" src="https://user-images.githubusercontent.com/5910851/50475161-fe3a0a00-09c3-11e9-9bce-a97c90d22fb4.png">

I think that `unknown-target` might confused many peoples as it's indicate as something goes wrong.

**Comment by erwindon** [comment]
This is a problem introduced salt 2018.3.x.
It has already been fixed, but a new release has not been issued yet.
There are already small workarounds in SaltGUI for issues in this area.
In this case the situation is correct while the job is still running, use `test.sleep 60` (async) to test.
I'm open for suggestions for a text replacement of `unknown-target`.

**Comment by dawidmalina** [comment]
As this is upstream issue: https://github.com/saltstack/salt/issues/48734 we can simply close it.
