### ISSUE TITLE
UX sync_pillar from pillar information page

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#106]
I think that it would be nice improvement if we could `sync_pillar` for particular minion from the pillar page by extending existing menu

<img width="922" alt="zrzut ekranu 2018-12-27 o 16 35 54" src="https://user-images.githubusercontent.com/5910851/50485416-84bb0f80-09f5-11e9-8e04-6476be2e743d.png">

**Comment by erwindon** [comment]
Can you please describe a use-case?

**Comment by dawidmalina** [comment]
The best best approach would be to extend menu on the pillar page details with menu item which will allows us to call `saltutil.sync_pillar`. We usually found this helpful (if you apply pillar from external side aka external pillars) to force sync up of the pillars.

**Comment by erwindon** [comment]
This is for a specific minion.
Is this useful for all minions also?

**Comment by dawidmalina** [comment]
Main goal is to have this per minion which can be refreshed from pillars details page. Similar to what i described in grains ticket. Use caae for this is to force sync if pillars are not yet as expected.

**Comment by erwindon** [comment]
I had the following choices:
1) On `/pillars` add `saltutil.sync_pillar` for `*` (top of page)
2) On `/pillars` add `saltutil.sync_pillar` for specific minion (on minion row)
3) On `/pillarsminion` add `saltutil.sync_pillar` for that minion (top of page)
So only (3) is actually desired, correct?

The command shows the following error returned form the minion when I try this:
`ERROR: Pillar modules can only be synced to masterless minions`
(help!)

**Comment by erwindon** [comment]
Should the page `/pillarsminion` be refreshed after the command was finished (and the run-box closed)?

**Comment by dawidmalina** [comment]
Yes, we should focus only on 3 option (`/pillarsminion` page) and in this case we should use command: `saltutil.refresh_pillar` and exactly :) page should be refreshed and run-box can be closed.

**Comment by erwindon** [comment]
see #126

**Comment by erwindon** [comment]
merged
