### ISSUE TITLE
UX sync_grains from grains information page

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#107]
I think that it would be nice improvement if we could `sync_grains` for particular minion from the grains page by extending existing menu

<img width="932" alt="zrzut ekranu 2018-12-27 o 16 37 42" src="https://user-images.githubusercontent.com/5910851/50485463-c1870680-09f5-11e9-8235-a53dae27a1bc.png">

**Comment by dawidmalina** [comment]
The best best approach would be to extend menu on the grains page details with new menu item which will allows us to call `saltutil.sync_grains`. We usually found this helpful (if you apply grains from master side) to force sync up of the grains.
<img width="930" alt="zrzut ekranu 2018-12-31 o 02 54 58" src="https://user-images.githubusercontent.com/5910851/50553475-cf63b280-0ca7-11e9-80eb-b7d5b224c45b.png">

**Comment by erwindon** [comment]
This is for a specific minion.
Is this useful for all minions also?

**Comment by erwindon** [comment]
I had the following choices:
1) On `/pillars` add `saltutil.sync_grains` for `*` (top of page)
2) On `/pillars` add `saltutil.sync_grains` for specific minion (on minion row)
3) On `/pillarsminion` add `saltutil.sync_grains` for that minion (top of page)
So only (3) is actually desired, correct?

That command behaves properly when I try this.

**Comment by erwindon** [comment]
Should the page `/pillarsminion` be refreshed after the command was finished (and the run-box closed)?

**Comment by dawidmalina** [comment]
Yes, we should focus only on 3rd option (`/grainsminion` page) and exactly :) page should be refreshed and run-box can be closed.

**Comment by erwindon** [comment]
see #126

**Comment by erwindon** [comment]
merged
