### ISSUE TITLE
Feature request: Job Template or Favourite Jobs

### ISSUE THREAD

**Issue by lostsnow** [erwindon/SaltGUI#11]
I'm using [SaltPad](https://github.com/Lothiraldan/saltpad/), but this repository is not currently maintained. It has a feature called "Job Template" that is very useful, that used to execute some common commands.

Can you add similar feature to execute some frequently used commands or jobs?

**Comment by erwindon** [comment]
should the saved information contain both the target and command information? or just the command?
saltgui is a client-side application. is saving in the browser's datastore sufficient? that fixes the information to one specific browser and it may be readable for others.

**Comment by erwindon** [comment]
I just studied the info for SaltPad. The templates are in the main configuration file. See https://github.com/Lothiraldan/saltpad/blob/master/settings.json.sample. It contains named tuples containing targettype, targetpattern, command and arguments. It should not be that much work to read a similar configuration file (whether in json or yaml) and apply it to the fields of the "run command" dialog box.
@lostsnow : you did not respond to the questions from May 22nd. Is the request still valid?

**Comment by lostsnow** [comment]
Yes, it is not very difficult work but very useful for frequently used commands.

**Comment by maerteijn** [comment]
@erwindon You mean that you can define the templates in the saltmaster master file configuration, and that you can use them in saltgui?  Pretty neat

**Comment by erwindon** [comment]
yes.
Thanks for SaltPad for the original idea.
Thanks for @lostsnow for the request.
