### ISSUE TITLE
UX keys information page

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#115]
I think that keys page can be more dedicated to keys then minion (in current version). If we could remove current content duplication: `Salt version`, `OS version` and introduce key fingerprint (https://docs.saltstack.com/en/latest/ref/wheel/all/salt.wheel.key.html#salt.wheel.key.finger). It can be simple fetched by adding new method in saltgui/static/scripts/api.js during keys iteration:
```
  getKey(id) {
    return this.apiRequest("GET", "/keys/" + id, {});
  }
```

To improve performance we could cache fingerprint of accepted minions and only fetch unaccepted keys.

**Comment by erwindon** [comment]
I want to get rid of the _high-level_ api calls, and use only direct api calls.
In this case that would mean replacing `/keys` with `wheel.key.finger` with parameter `"*"` and still get all keys at once.
For rejected/denied/unaccepted keys no version information is shown (and cannot be shown). That leaves space to show the key.
Still not perfect.

**Comment by erwindon** [comment]
superseded by #159
