### ISSUE TITLE
UX recent jobs improvements

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#116]
It would be nice improvement if we could really see status of recent jobs. What we could do is limit the number of jobs that are treated as recent and fetch for this jobs detailed information by executing sub request `jobs.list_jobs_filter 10` and then `jobs.list_job xxxxxxxx`

**Comment by dawidmalina** [comment]
I totally agree with you - as I didn't thought about multiple operators in the same time.

**Comment by erwindon** [comment]
See issue #180 and PR #205
