### ISSUE TITLE
choose public-ip when multiple ip numbers visble

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#117]
An IP number is shown to properly identify a minion.
The information is taken from grain `fqdn_ip4`.
Under certain circumstances, multiple IP numbers are visible.
e.g. `10.0.0.5,167.254.168.54` (redacted)
only the first IP number should be used.
This has been solved in #121.

The selection of the IP number is a bit arbitrary.
At least public IP numbers should take priority over private IP numbers.

**Comment by dawidmalina** [comment]
I don't think that just picking the first one is the best option. Example in my case:
```
sudo salt-call grains.get fqdn_ip4
local:
    - 127.0.1.1
    - 10.122.146.5
```

As you see it will return localhost :) Basically this value returns all ips which are related to minion hostname. So maybe instead of guessing better print all of them?

**Comment by erwindon** [comment]
continued as PR #131

**Comment by erwindon** [comment]
@dawidmalina can you please verify this one on branch `ipnumber`? Now, 10.122.146.5 should be displayed instead.

**Comment by dawidmalina** [comment]
LGTM

**Comment by dawidmalina** [comment]
Somehow it broke the pillars page (on the master branch it's ok):
<img width="924" alt="zrzut ekranu 2019-01-4 o 02 00 56" src="https://user-images.githubusercontent.com/5910851/50669310-a8b5bc80-0fc4-11e9-9bf5-237b6505a30d.png">

**Comment by erwindon** [comment]
THX!
I missed one null-pointer validation...
merged
