### ISSUE TITLE
icons for OS

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#123]
See branch `osicons` for icons with OS information.
@dawidmalina Which OS(s) are you using? I have Windows+CentOS, Docker has Debian+Ubuntu.

**Comment by dawidmalina** [comment]
Great :+1: I'm using CentOS and Ubuntu. I can extend docker environment with CentOS do we will have 3 minions and 3 oses. Will drop pull request later today.

**Comment by erwindon** [comment]
merged (without PR)

**Comment by erwindon** [comment]
this is what it looks like:
![afbeelding](https://user-images.githubusercontent.com/3663742/50663697-c83feb80-0faa-11e9-93e2-5f998bd7b4de.png)
