### ISSUE TITLE
Add CentOS based minion to environment in docker

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#124]
We could extend minion lists with CentOS based minion to environment in docker.

**Comment by dawidmalina** [comment]
<img width="922" alt="zrzut ekranu 2019-01-1 o 18 29 57" src="https://user-images.githubusercontent.com/5910851/50574967-4eb1cd00-0df3-11e9-87e8-96aaa542cf49.png">

**Comment by erwindon** [comment]
Since I'm the current maintainer, I'll push the new docker images.

**Comment by dawidmalina** [comment]
Cool, are you able to use same user in docker hub? Or we will have new user under your name?

**Comment by erwindon** [comment]
I already have a docker account. So I'll put everything on my name.
I've updated all 4 dockerfiles with my details, replacing maerteijn(3x) and dawidmalina(1x).
Now (re)creating all 4 images.

on `dockerfile-saltmaster`:
```
Step 11/14 : COPY ./conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY failed: stat /var/lib/docker/tmp/docker-builder300735442/conf/supervisord.conf: no such file or directory
```
(working on the other 3)

**Comment by erwindon** [comment]
closing this one, see #125 for further developments
