### ISSUE TITLE
Inconsistency in arrows for drop down menu

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#129]
In most pages arrow which indicate drop down menu looks like this: ►
But on the command run page we have this: ▼

It would be nice to have the same arrows everywhere. Maybe we could have this ► arrow when drop down menu is not opened and ▼ when menu is opened.

Another idea would be to have three green dots and menu like this: https://i.stack.imgur.com/NlHMN.gif

**Comment by dawidmalina** [comment]
Maybe we could use some exiting open source icons? For example: https://material.io/tools/icons/

They have also very nice web templates which can be reused. What do you think?

**Comment by dawidmalina** [comment]
:(

**Comment by erwindon** [comment]
I'll change the dropdown menuindicator to ☰.

**Comment by dawidmalina** [comment]
I recently added also ability to change from ☰ to x when drop down menu is opened. If you are interested I can drop pull request.

**Comment by erwindon** [comment]
Depends on both visual and coding elements... So, let me see it in the PR...

**Comment by erwindon** [comment]
The dropdown menu icon has been updated in regular commit cac4db50c128cae3700057b9716dc99c82ab248b, closing this issue.

**Comment by dawidmalina** [comment]
https://github.com/erwindon/SaltGUI/pull/135
