### ISSUE TITLE
add user hello message

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#130]
It would be nice to have welcome message which will print `Hello <user>` with drop down menu to logout. Small gimp based screen :)
<img width="1440" alt="zrzut ekranu 2019-01-3 o 15 53 28" src="https://user-images.githubusercontent.com/5910851/50644235-8b570300-0f70-11e9-88b7-e6f3dbbb6311.png">

**Comment by erwindon** [comment]
Sorry, I see no benefit. And this cannot be applied to narrow screens where the menu is already a drop-down menu.

**Comment by dawidmalina** [comment]
:(
