### ISSUE TITLE
removal of nanoseconds in job start time

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#140]
Removal of nanoseconds in job start time does not bring any value and I think that can be removed.

**Comment by erwindon** [comment]
I will develop this.

**Comment by erwindon** [comment]
Note to self: Add parameter to `saltgui_datetime_fraction_digits` to `master` file. Valid values 0..6. Default value is 6 to get standard behavior. All datetime fields should honor this. value 0 should not use `.`.

**Comment by erwindon** [comment]
Continued as PR #151
