### ISSUE TITLE
dedicated job template page

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#145]
It would be nice to have dedicate job template page where all configured templates will be displayed.
In addition page will allows us to apply particular template (forward to run command with needed inputs filled up automatically).

This is proposition (mockup) which I can work on:
![zrzut ekranu 2019-01-20 o 20 43 41](https://user-images.githubusercontent.com/5910851/51444177-7c07e180-1cf4-11e9-93e7-19ab956f3e31.png)

When user will not have any templates message `No job template found` should be displayed instead.

**Comment by erwindon** [comment]
Should this replace the current template menu?

**Comment by erwindon** [comment]
I prefer hiding the menu item when no templates are present

**Comment by erwindon** [comment]
I'm still in doubt on whether to allow this functionality, Therefore not labelled as work-in-progress,

**Comment by erwindon** [comment]
Schedules are a built-in feature, and therefore well-known. Also you can create the first schedules using SaltGUI. Templates are unknown, and they cannot created using our gui. Therefore do not bother the user with it until it is actually used

**Comment by dawidmalina** [comment]
Can you assign this task for me? I will code this if you don't mind.

**Comment by erwindon** [comment]
> The implementation also supports the targettype value. Please include that too.
Same way as elsewhere. The targettype and target can appear in one column. Note that there is a dedicated function to combine these 2 into one presentation value. That function always leaves out the GLOB and LIST types because the user can derive that from the actual value.
