### ISSUE TITLE
new jobs page does not show statistics on running jobs

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#154]
**Is your feature request related to a problem? Please describe.**
The jobs summary on many pages shows for which jobs the minions are still working. This functionality is not present on the jobs page

**Describe the solution you'd like**
Add the jobs summary as a new column on the jobs page.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by dawidmalina** [comment]
If you will give me more details what exactly you would like to have I can work on this.

**Comment by erwindon** [comment]
The jobs panel shows 7 jobs with 3 values: target, function and starttime.
For jobs that are still running it shows how many minions are already done and how many are still running the command.
The info is retrieved last, and it may take a few seconds before it is shown.
Here is a sample:
![afbeelding](https://user-images.githubusercontent.com/3663742/51804982-f510b700-2267-11e9-91f6-b9a08a3f0549.png)

The suggested solution for the Jobs page is to add a column right of the dropdownmenu button that shows this. Column title is "Status". Do not combine with the target info as done in the jobs panel.

**Comment by dawidmalina** [comment]
Currently only minions and keys page run this `minions.router.api.getJobsActive().then(minions._runningJobs);` onShow. I've added this to jobs page but I didn't add this to page content. I think that this should be added to all pages to be consistent. @erwindon what do you think?

**Comment by erwindon** [comment]
yes, the side-panel for jobs should behave identical wherever it is located.

**Comment by dawidmalina** [comment]
It will look like this:
![zrzut ekranu 2019-01-31 o 01 17 39](https://user-images.githubusercontent.com/5910851/52021707-64033f80-24f6-11e9-9906-923cf2ed8bb2.png)

**Comment by erwindon** [comment]
will be closed automatically when the PR is done
