### ISSUE TITLE
dedicated minion status column

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#160]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Currently the only way we can define whether minion is offline or online based on ip column. Which is basically ok but it would be easier if we could introduce dedicated status column (up / down or online / offline).

**Describe alternatives you've considered**
Leave as is :)

**Additional context**

**Comment by erwindon** [comment]
I see no benefit in removing the ip values.

**Comment by dawidmalina** [comment]
Can we at least be consistent on all pages? When minion is responding then in status column we are presenting minion ip.

Currently it's looks like this:

Page | Columnt Name | Value
-----|--------------|------
minions | status | ip
keys | satus | ip
grains | satus | ip
schedules | satus | accepted
pillars | satus | accepted

**Comment by dawidmalina** [comment]
@erwindon so my proposition is to keep this as is but just a tune status value for `scheduler` and `pillars` page and instead `accepted` add `online`. What do you think?

**Comment by dawidmalina** [comment]
Ok it's still cosmetic - I can accept what we have now :)
