### ISSUE TITLE
allow to display custom grains

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#161]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In our case we are configuring two quite important grains for each nodes (`environment` and `roles`).
First is just a regular string and 2nd is just a list of roles that minion have. It would be nice to allow (probably via master configuration) users to configure which additional grains should be display on grains page.

**Describe alternatives you've considered**
Alternatively it could be display on minions page as well.

**Additional context**

**Comment by erwindon** [comment]
I previously spent a lot of effort to determine which grains were custom grains and which ones were standard grains. Found no way to do that automatically. But a bit of optional configuration is ok.
Propose to add new key `saltgui_preview_grains` in the master file. When present, the values for the keys in that list will be added in a new column, right of the menu button. grain names will not be shown, only their values in a simple comma separated format.
e.g. "ENV1", ["ROLE1", "ROLE2"]

**Comment by erwindon** [comment]
@dawidmalina is this useable?

**Comment by dawidmalina** [comment]
I would like to have dedicated columns to benefit from existing sorting capabilities.
