### ISSUE TITLE
retry for RUNNER/WHEEL commands does not work properly

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#168]
**Describe the bug**
Recently, a retry feature was added.
Due to a bug in Salt, the target `unknown-target` is ignored.
For RUNNER and WHEEL commands, the target `hostname_master` is stored. Where _hostname_ is the actual hostname.

**To Reproduce**
1. Run any wheel command, e.g. `wheel.file_roots.list_roots` (don't try any of the usual ones, because these are suppressed anyway)
2. Go to the `jobs` page
3. Select `Re-run job...`

**Expected behavior**
Ignore these values and use an empty string.

**Comment by dawidmalina** [comment]
What exact error do you see. To be honest I'm able to rerun this job even if target is `hostname_master`. Check this output (only first job was run manually):
![zrzut ekranu 2019-02-3 o 11 42 19](https://user-images.githubusercontent.com/5910851/52175749-d0a56500-27a8-11e9-9952-0901c1c897d4.png)

![zrzut ekranu 2019-02-3 o 11 43 21](https://user-images.githubusercontent.com/5910851/52175758-edda3380-27a8-11e9-8007-92d0ecab60fc.png)

**Comment by erwindon** [comment]
for all RUNNER commands, the (then optional) target is ignored.
for WHEEL commands, SaltGUI treats the (then required) target as the named variable `match`. That variable is only recognized by (mostly) the `wheel.key` commands. those commands will then see different parameters when retried.
