### ISSUE TITLE
Api call for /keys on minion related pages

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#169]
**Describe the bug**
On all minion related pages we are always calling `/keys` which is not needed to properly generate those pages.

**To Reproduce**
1. Go to one of this pages:
- /
- /grains
- /schedules
- /pillars
2. Click on firebug / network tab
3. See request to `/keys`

**Expected behavior**
Keys call to api is not needed and we should remove all unused code.

**Comment by erwindon** [comment]
but it is needed...
`/keys` provides a much faster answer than the calls actually related to the page.
especially when there is at least one unresponsive minion (50% of my minions are shutdown).
