### ISSUE TITLE
Top menu is not visible on small screen

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#176]
**Describe the bug**
Somewhere during recent development top menu has been broken. It's not visible.

**To Reproduce**
1. Go to 'main page'
3. Shrink the browser size to less then 800px

**Expected behavior**
Top menu (dedicated) should be visible.

**Screenshots**
![zrzut ekranu 2019-02-10 o 11 16 53](https://user-images.githubusercontent.com/5910851/52532463-fc36cb00-2d25-11e9-90a5-529a2065ca79.png)

**Comment by erwindon** [comment]
bisecting now...

**Comment by erwindon** [comment]
problem is in cb64a5be7ec681c1e2b9752f921f713b80afd472
you removed `height: 51px` from file `main.css`.
please fix

**Comment by erwindon** [comment]
I recommend something like `overflow: auto`

**Comment by dawidmalina** [comment]
Yes, it was removed during pull request review: https://github.com/erwindon/SaltGUI/pull/163#discussion_r252904792. I will try to bring it back but fix the mentioned  by you 2px gap with dd menu.

**Comment by erwindon** [comment]
see #178
