### ISSUE TITLE
Switch to NPM

### ISSUE THREAD

**Issue by smarletta** [erwindon/SaltGUI#187]
**Is your feature request related to a problem? Please describe.**
Yarn has a calling home feature and sends statistics to Facebook. Not sure but in EU it could be against privacy law. Furthermore NPM got more and more stable the last years. I would like to go back to NPM to be as close as possible to the NodeJS stack and reduce usage of external tools.

**Describe the solution you'd like**
Should be easily doable: Small fixes in package.json, runtests,sh and remove yarn's lockfile which will be exchanged with native package-lock.json

**Describe alternatives you've considered**
For now I see no alternatives.

**Additional context**
PR is: https://github.com/erwindon/SaltGUI/pull/188

**Comment by erwindon** [comment]
Please transfer all information from this issue to the PR.
It is not really needed to create an issue when you start with a PR.
Just put the word "WIP" in front of the PR title while it is not ready for merge yet.

**Comment by erwindon** [comment]
all information is in PR #188
