### ISSUE TITLE
Remove yarn.lock and add package-lock

### ISSUE THREAD

**Issue by smarletta** [erwindon/SaltGUI#191]
**Is your feature request related to a problem? Please describe.**
After switching to npm we can get rid of the yarn.lock and use regular package-lock.json

**Describe the solution you'd like**
Remove old file and added new file.

**Describe alternatives you've considered**
none

**Additional context**
PR is: https://github.com/erwindon/SaltGUI/pull/192

**Comment by erwindon** [comment]
files are no longer present
