### ISSUE TITLE
Invalid promise handling

### ISSUE THREAD

**Issue by smarletta** [erwindon/SaltGUI#195]
**Describe the bug**
Several problems in Promise handling

**To Reproduce**
Are not needed

**Expected behavior**
Promises should also tackle the rejection case. This is mostly not given. 

**Example**
```javascript
if(route.onShow) response = route.onShow();
```

It is never checked if inner promises resolve or not.

**Additional context**
reason could be found in bad test design.

if I will find time after the Webpack PRs i can tackle this issues.

**Comment by erwindon** [comment]
> if I will find time after the Webpack PRs i can tackle this issues.
that would be great!
re-assigning back to you...

**Comment by erwindon** [comment]
@smarletta are you working on this one?

**Comment by smarletta** [comment]
Will fetch later latest Master and try to solve it the next days.

Erwin Dondorp <notifications@github.com> schrieb am So., 31. März 2019,
13:40:

**Comment by erwindon** [comment]
@smarletta do you have any new planning/target?

**Comment by erwindon** [comment]
we seem to have lost contact with @smarletta 
but the problem is valid, so it needs to be solved/improved.
