### ISSUE TITLE
functional tests failing

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#202]
**Describe the bug**
Command `npm run test:functional` fails. It is unclear why that one fails. It looks like mocha is not processing any JS code.

**To Reproduce**
1. Run 'bash runtests.sh' (or at least the part starting at `docker-compose`)
2. See error

**Expected behavior**
A successful functional tests composed of 4 steps.

**Additional context**
Help wanted, as my knowledge in this area is very limited...

**Comment by dawidmalina** [comment]
I found the issue. Nightmare does not support modules. (check https://jakearchibald.com/2017/es-modules-in-browsers/)

We need to use as fallback this entry:
```
<script nomodule src="fallback.js"></script>
```

**Comment by erwindon** [comment]
or use babel again to translate

**Comment by erwindon** [comment]
something changed in Travis to made things working again.
our professional statement for this is: "solved by waiting a while"
we're happy and this one is closed now
