### ISSUE TITLE
Local IP addresses of Salt Minions are not being reflected correctly in the main page listing

### ISSUE THREAD

**Issue by jonathanuntalan-rfg** [erwindon/SaltGUI#211]
Some local IP addresses of Salt Minions are not being reflected correctly in the main page listing. 

99% of the wrong entries were corrected after changing this line of code:
https://github.com/erwindon/SaltGUI/blob/6f452723c3c6af40bfd9aafc2dc2adb1e08aa292/saltgui/static/scripts/routes/Page.js#L71

with the ff. line:

    const ipv4 = minion.ipv4;
     
It should be noted that the first entry of the Array list being returned from issuing _salt "*" grains.item fqdn_ip4_ is different from the first entry of the Array list being returned from issuing _salt "*" grains.item ipv4_. This update is just a rough patch on my side. I hope you'll come up with a better idea. Thanks.

**To Reproduce**
1. Login to SaltGUI.
2. Check the IP addresses being reflected in the Status column in the main page.

**Expected behavior**
It should show the actual local IP addresses of the Salt Minions.

**Screenshots**

Using fdqn_ip4, Local IP addresses are not being shown correctly:

![Page js_Using_fqdn_ip4](https://user-images.githubusercontent.com/49468097/55852971-a77ec780-5b91-11e9-8e1f-df5a1d49bb05.png)

Using ipv4, 99% of Local IP addresses are being shown correctly:

![Page js_Using_ipv4](https://user-images.githubusercontent.com/49468097/55852981-ac437b80-5b91-11e9-8ce9-61b0a31f363f.png)

**Additional context**

**Comment by erwindon** [comment]
jonathan,
By design SaltGUI tries to display the external ip-address.
In this case it has only local IP numbers available. And it then makes a random choice.
Can you provide some samples of the IPv4 related grain values `fqdn_ip4` and `ipv4` from some of the minions? e.g. the output from `grains.item fqdn_ip4 ipv4` would be nice. of course stripping all the minion names is fine.

**Comment by erwindon** [comment]
Jonathan,
By design SaltGUI tries to display the external ip-address from the available addresses.
In this case it has only local IP numbers available. And it then makes a random choice.
Can you provide some samples of the IPv4 related grain values `fqdn_ip4` and `ipv4` from (some of) the minions? e.g. the output from `grains.item fqdn_ip4 ipv4` would be nice. of course stripping all the minion names is fine.

**Comment by jonathanuntalan-rfg** [comment]
Here's a snapshot:

![ipv4_vs_fqdn_ip4](https://user-images.githubusercontent.com/49468097/55922635-afdc0e80-5c34-11e9-86ea-f41717d05350.png)

**Comment by jonathanuntalan-rfg** [comment]
Here's a snapshot:

![ipv4_vs_fqdn_ip4](https://user-images.githubusercontent.com/49468097/55922748-2547df00-5c35-11e9-8b70-e55a5bbec1b7.png)

**Comment by erwindon** [comment]
jonathan,
As I suspected, your installation uses only private ip-numbers.
And `ipv4` contains the same ip-numbers as `ipv4_fqdn`, except for the additional `127.0.0.1` and the order of the items within these items is not consistent.
I can make this a bit more predictable, by using different priorities for the different network classes (see https://nl.wikipedia.org/wiki/RFC_1918). But also then, I would prefer to list the C-class first, then the B-class, then the A-class and finally the local class. And that would still not be your preference.
So, an extra condition will be added: we will only choose an IP numbers from the class that has the least duplicates.  In your case, C-class has duplicates as 192.168.122.1 appears for 3 minions and should be ignored. B-class has duplicates as 172.17.0.1 appears for 2 minions and should be ignored. A-class does not have duplicates. Therefore we can chose to show that one.
Updating this from `bug` to `enhancement`.

**Comment by erwindon** [comment]
jonathan,
I made a change to SaltGUI to display the IP numbers as discussed in the previous comment.
It is on my branch `ipnrdisplay`.
Can you give it a quick test?

**Comment by jonathanuntalan-rfg** [comment]
Hi Erwin,

Looks like it's working except for the 127.0.1.1 duplicates. Please refer to screenshots below:

![Page js_Using_fqdn_ip4_revised_ipnrdisplay](https://user-images.githubusercontent.com/49468097/56177585-bc47d900-6031-11e9-8286-8acee1228c12.png)
![Minion_Console1](https://user-images.githubusercontent.com/49468097/56177606-c8339b00-6031-11e9-8b95-bfd7075a4339.png)
![Minion_Console3](https://user-images.githubusercontent.com/49468097/56177612-d386c680-6031-11e9-947b-6a458c413810.png)

**Comment by erwindon** [comment]
Jonathan,
can you give me the output of `grains.item fqdn_ip4 ipv4` so I can use that as test data?
not as an image but as text.
feel free to remove any sensitive data from it.
and never mind whether it remains valid json or not.

**Comment by erwindon** [comment]
you provided another screenshot by mail.
that one looks much better, so I assume that all is well.

but you also reported that 2 minions show as 127.0.1.1.
now grain `fqdn_ip4` only returns that value, so it has no other choice and it works as intended.
the reason that `fqdn_ip4` does not return anything else is likely because the host file (and/or dns) of that machine does not have an entry for the hostname of the machine itself.

**Comment by erwindon** [comment]
p.s. you need to restart the salt-minion after changes to the hosts file...

**Comment by jonathanuntalan-rfg** [comment]
{
    "fqdn_ip4": [
        "172.17.0.1",
        "192.168.122.1",
        "10.100.20.61"
    ],
    "ipv4": [
        "10.100.20.61",
        "127.0.0.1",
        "172.17.0.1",
        "192.168.122.1"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "10.100.20.119",
        "172.20.0.1",
        "172.23.0.1",
        "172.18.0.1",
        "172.19.0.1",
        "172.17.0.1",
        "172.21.0.1",
        "192.168.122.1",
        "172.24.0.1"
    ],
    "ipv4": [
        "10.100.20.119",
        "127.0.0.1",
        "192.168.122.1"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "172.21.0.1",
        "172.20.0.1",
        "172.22.0.1",
        "172.18.0.1",
        "172.24.0.1",
        "10.100.20.91",
        "172.17.0.1",
        "10.100.40.68",
        "192.168.122.1"
    ],
    "ipv4": [
        "10.100.20.91",
        "10.100.40.68",
        "127.0.0.1",
        "172.17.0.1",
        "172.18.0.1",
        "172.20.0.1",
        "172.21.0.1",
        "172.22.0.1",
        "172.24.0.1",
        "192.168.122.1"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "10.100.20.43",
        "172.17.0.1",
        "192.168.122.1",
        "192.168.201.125"
    ],
    "ipv4": [
        "10.100.20.43",
        "127.0.0.1",
        "172.17.0.1",
        "192.168.122.1",
        "192.168.201.125"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "10.100.20.129",
        "172.17.0.1",
        "192.168.122.1",
        "172.19.0.1",
        "172.18.0.1"
    ],
    "ipv4": [
        "10.100.20.129",
        "127.0.0.1",
        "172.17.0.1",
        "172.18.0.1",
        "172.19.0.1",
        "192.168.122.1"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "10.100.20.77",
        "172.18.0.1",
        "172.19.0.1",
        "172.17.0.1",
        "192.168.201.159",
        "192.168.122.1"
    ],
    "ipv4": [
        "10.100.20.77",
        "127.0.0.1",
        "172.17.0.1",
        "172.18.0.1",
        "172.19.0.1",
        "192.168.122.1",
        "192.168.201.159"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "10.100.20.64",
        "172.17.0.1",
        "192.168.122.1"
    ],
    "ipv4": [
        "10.100.20.64",
        "127.0.0.1",
        "172.17.0.1",
        "192.168.122.1"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "192.168.122.1",
        "10.100.20.133"
    ],
    "ipv4": [
        "10.100.20.133",
        "127.0.0.1",
        "192.168.122.1"
    ]
}
: (no response)
: ▽
{
    "fqdn_ip4": [
        "10.100.20.59"
    ],
    "ipv4": [
        "10.100.20.59",
        "127.0.0.1"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "10.5.0.1",
        "10.100.20.85",
        "192.168.122.1",
        "172.17.0.1",
        "172.18.0.1"
    ],
    "ipv4": [
        "10.5.0.1",
        "10.100.20.85",
        "127.0.0.1",
        "172.17.0.1",
        "172.18.0.1",
        "192.168.122.1"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "172.18.0.1",
        "10.100.20.48",
        "172.17.0.1",
        "192.168.122.1",
        "10.5.0.1"
    ],
    "ipv4": [
        "10.5.0.1",
        "10.100.20.48",
        "127.0.0.1",
        "172.17.0.1",
        "172.18.0.1",
        "192.168.122.1"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "192.168.122.1",
        "172.17.0.1",
        "10.100.20.124",
        "172.18.0.1"
    ],
    "ipv4": [
        "10.100.20.124",
        "127.0.0.1",
        "172.17.0.1",
        "172.18.0.1",
        "192.168.122.1"
    ]
}
: (no response)
: ▽
{
    "fqdn_ip4": [
        "10.100.20.60",
        "127.0.0.1"
    ],
    "ipv4": [
        "10.100.20.60",
        "127.0.0.1"
    ]
}
: (no response)
: ▽
{
    "fqdn_ip4": [
        "172.21.0.1",
        "172.20.0.1",
        "172.18.0.1",
        "172.19.0.1",
        "172.17.0.1",
        "192.168.122.1",
        "10.100.20.47"
    ],
    "ipv4": [
        "10.100.20.47",
        "127.0.0.1",
        "172.17.0.1",
        "172.18.0.1",
        "172.19.0.1",
        "172.20.0.1",
        "172.21.0.1",
        "192.168.122.1"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "192.168.122.1",
        "10.100.20.63"
    ],
    "ipv4": [
        "10.100.20.63",
        "127.0.0.1",
        "192.168.122.1"
    ]
}
: ▽
{
    "fqdn_ip4": [
        "10.100.40.36",
        "192.168.122.1",
        "172.17.0.1",
        "10.100.20.105"
    ],
    "ipv4": [
        "10.100.20.105",
        "10.100.40.36",
        "127.0.0.1",
        "172.17.0.1",
        "192.168.122.1"
    ]
}

**Comment by erwindon** [comment]
thx for the test data!
Your network is not consistent.
You cannot be using a common A-class network because 2 minions use 10.5.0.1.
You cannot be using a common B-class network because e.g. 12 minions use 172.17.0.1.
You cannot be using a common C-class network because 14 minions use 192.168.122.1.
Since no common network can be determined, SaltGUI cannot select IP numbers only from that network. It then picks a C-class address when available. otherwise a B-class address when available, otherwise an A-Class address when available. otherwise just the first IP number.

**Comment by jonathanuntalan-rfg** [comment]
Reconfiguring the /etc/hosts of each minion is not under my set of options. I'm also using Kolide Fleet Manager/OSQuery and these tools have no issues or whatsoever in harvesting all the private IP addresses. Salt Stack should probably provide more granulized grains for this. Thanks anyway.

**Comment by erwindon** [comment]
Has any network mask or ip number pattern been configured in those tools?
For the human eye, it is clear that `10.100.20.x` is the unique network. It requires a more extensive algorithm in SaltGUI to figure that out. I may give that a try in the next days. B- and C-subnets should be easy to detect...

**Comment by erwindon** [comment]
@jonathanuntalan-rfg 
I've added some more intelligence to SaltGUI.
It now first determines the common subnet(s) for the IP-numbers.
Then when IP-numbers are show, it chooses a number from a common subnet first.
With your test data it gives a consistent result.
As before the candidate is on branch `ipnrdisplay`.
Can you please confirm that it provides a useable result?
