### ISSUE TITLE
How could I run this project on my local machine

### ISSUE THREAD

**Issue by rumo19** [erwindon/SaltGUI#213]
Dear Dondorp,

SALT GUI project is very interesting to me. How could I work on it? I found out that you are using vanilla ES6 and rest_cherrypy server. How could I run this project in my local machine? I already installed saltstack and salt-api in my machine. I am wondering how could I integrate my salt-server to your project.
Thank you.
Regards
Kamrul

**Comment by erwindon** [comment]
The description in https://github.com/erwindon/SaltGUI#quick-start-using-pam-as-authentication-method should be sufficient. Let me know when that is unclear or incomplete.

**Comment by rumo19** [comment]
ok, Thanks. I will try and give you a feedback.

**Comment by rumo19** [comment]
When I  execute runtest.sh, It shows like this:
audited 4837 packages in 12.914s
found 0 vulnerabilities


> saltgui-test@0.0.1 eslint /srv/SaltGUI
> eslint saltgui/static/scripts tests/


> saltgui-test@0.0.1 stylelint /srv/SaltGUI
> stylelint 'saltgui/static/stylesheets/*.css'


> saltgui-test@0.0.1 test:coverage /srv/SaltGUI
> nyc mocha --require @babel/register --trace-warnings --check-leaks --reporter spec tests/unit/



  Unittests for Output.js
    ✓ test formatJSON
    ✓ test formatYAML
    ✓ test formatNESTED
    ✓ test isDocumentationOutput
    ✓ test isDocuKeyMatch
    ✓ test reduceDocumentationOutput
    ✓ test documentation external link conversion

  Unittests for ParseCommandLine.js
    ✓ test parseCommandLine

  Unittests for TargetType.js
    ✓ test makeTargetText

  Unittests for Utils.js
    ✓ test getQueryParam2


  10 passing (335ms)

----------------------------|----------|----------|----------|----------|-------------------|
File                        |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------------------|----------|----------|----------|----------|-------------------|
All files                   |    13.73 |     18.1 |        0 |    13.13 |                   |
 scripts                    |     15.7 |    20.49 |        0 |    15.63 |                   |
  Api.js                    |        0 |        0 |        0 |        0 |... 79,181,183,186 |
  CommandBox.js             |        0 |        0 |        0 |        0 |... 01,306,308,309 |
  Documentation.js          |        0 |        0 |        0 |        0 |... 88,89,92,94,95 |
  DropDown.js               |     2.04 |        0 |        0 |     2.33 |... 77,78,86,90,94 |
  ParseCommandLine.js       |      100 |      100 |      100 |      100 |                   |
  Router.js                 |        0 |        0 |        0 |        0 |... 09,210,212,214 |
  RunType.js                |        0 |        0 |        0 |        0 |... 30,33,37,38,39 |
  TargetType.js             |    10.91 |     12.9 |      100 |    11.11 |... 01,105,106,107 |
  Utils.js                  |    66.67 |    71.43 |      100 |    59.09 |... 31,32,33,34,39 |
  index.js                  |        0 |        0 |        0 |        0 |                   |
 scripts/output             |    32.72 |    33.19 |        0 |    32.14 |                   |
  Output.js                 |     6.81 |     2.67 |        0 |     6.83 |... 19,421,424,427 |
  OutputDocumentation.js    |    88.07 |       80 |      100 |    89.29 |... 56,157,173,174 |
  OutputHighstate.js        |     1.49 |        0 |        0 |     1.71 |... 82,183,184,186 |
  OutputJson.js             |      100 |      100 |      100 |      100 |                   |
  OutputNested.js           |      100 |     91.3 |      100 |      100 |          17,41,58 |
  OutputSaltGuiHighstate.js |     0.56 |        0 |        0 |      0.7 |... 59,262,263,266 |
  OutputYaml.js             |    91.18 |    83.93 |      100 |      100 |... 33,34,35,37,95 |
 scripts/routes             |     0.16 |        0 |        0 |     0.18 |                   |
  Grains.js                 |        0 |        0 |        0 |        0 |... 25,128,132,133 |
  GrainsMinion.js           |        0 |        0 |        0 |        0 |... 88,92,93,95,97 |
  Job.js                    |        0 |        0 |        0 |        0 |... 28,129,130,132 |
  Jobs.js                   |        0 |        0 |        0 |        0 |... 11,212,213,214 |
  Keys.js                   |        0 |        0 |        0 |        0 |... 86,187,192,193 |
  Login.js                  |        0 |        0 |        0 |        0 |... 69,70,71,75,76 |
  Minions.js                |        0 |        0 |        0 |        0 |... 89,90,92,96,97 |
  Page.js                   |        0 |        0 |        0 |        0 |... 87,389,393,394 |
  Pillars.js                |        0 |        0 |        0 |        0 |... 79,80,82,86,87 |
  PillarsMinion.js          |        0 |        0 |        0 |        0 |... 27,128,133,134 |
  Route.js                  |      2.5 |        0 |        0 |      2.9 |... 32,135,136,140 |
  Schedules.js              |        0 |        0 |        0 |        0 |... 11,113,117,118 |
  SchedulesMinion.js        |        0 |        0 |        0 |        0 |... 26,129,130,131 |
  Templates.js              |        0 |        0 |        0 |        0 |... 75,76,79,81,85 |
----------------------------|----------|----------|----------|----------|-------------------|
I do not understand this things. How could I find the user login interface? 
This is my sample settings:
rest_cherrypy:
  port: 8000
  host: 127.0.0.1
  disable_ssl: true
  app: /srv/SaltGUI/saltgui/index.html
  static: /srv/SaltGUI/saltgui/static
  static_path: /static
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
  debug: false

external_auth:
  pam:
    test:
      - .*

**Comment by erwindon** [comment]
`runtests.sh` is a tool for automated tests with the following steps:
* eslint: verifies the javascript. here, no errors/warnings are shown --> good
* stylelint: verifies the css. here, no errors/warnings are shown --> good
* unittests: verifies some non-gui code, no errors/warnings are shown --> good
* the table shows the coverage of the unit tests. it shows that we have some work here
* the next step would have been a functional test; but these test currently cannot be run until #202 is fixed

The user-interface can be seen by using a web-browser and navigating to http://127.0.0.1:8000 as indicated by the `host` and `port` settings. Update the setting for `host` to `0.0.0.0` to make the GUI available from other machines.

Unless you actually installed the software directly under `/srv`, you should update the `master` file so that the `app` and `static` entries are actually pointing to the installed software.

Note that you need to restart salt-api after configuration changes...

**Comment by erwindon** [comment]
@rumo19 I assume this question is resolved. feel free to re-open it when you have more questions. or open a new one when the question/suggestion is unrelated
