### ISSUE TITLE
Hide scheduled jobs

### ISSUE THREAD

**Issue by elipsion** [erwindon/SaltGUI#223]
**Is your feature request related to a problem? Please describe.**
When viewing the list of jobs, I would like to be able to hide scheduled jobs; such as `event.fire{ 
 ... } grains_refresh` and `mine.update`

**Describe the solution you'd like**
A check-box (or several) to hide recurring or otherwise noisy jobs.

**Describe alternatives you've considered**
None

**Comment by erwindon** [comment]
@elipsion 
Is PR #224 a useable implementation for this request?

**Comment by elipsion** [comment]
I guess this is as good as it gets without making changes to Salt proper.

Salt seems to have a ~1MB limit on the response on `jobs.list_jobs`, and no way of making negative/excluding filters on the back-end.
