### ISSUE TITLE
Serve SaltGUI from different host then salt master

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#238]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could configure saltgui on different host then salt master/api.

So basicaly I would like to decauple ui (and serve it from nginx) from salt master/api. This of course should not be mandatory.

**Describe the solution you'd like**
A way to inject config like `apiurl` which will point to proper salt master/api endpoint.

**Describe alternatives you've considered**

**Additional context**

**Comment by dawidmalina** [comment]
@erwindon I can contribute this but I would like to have some hints from you according implementation.

**Comment by erwindon** [comment]
> A way to inject config like apiurl which will point to proper salt master/api endpoint.

The normal way for configuration is the `master` file. But that is not possible in this case, as the master file cannot be found yet. I think a simple JS include file with the required config should be used. On default installations the file is unchanged.

I think someone already tried this out. I remember seeing some code in one of the forks. Was that you?

Just set up a PR on a new branch. with a minimal solution. I'll comment on it until it is acceptable for merge with possibly some further development by myself.
