### ISSUE TITLE
Job output is green when hosts fail

### ISSUE THREAD

**Issue by elipsion** [erwindon/SaltGUI#242]
**Describe the bug**
When a job fails, the colour is different on SaltGUI compared to Salt console output

**To Reproduce**
1. `sudo salt saltmaster cmd.run "echo foobar >&2 && /bin/false"` 
2. See error

**Expected behavior**
I expect hostname to have other colour than green when jobs fail.

**Screenshots**
![image](https://user-images.githubusercontent.com/714809/59963015-7bff4e00-94ed-11e9-8529-f43a9ec6f52d.png)
![image](https://user-images.githubusercontent.com/714809/59963032-9afde000-94ed-11e9-8f8f-4ec8289beb87.png)

**Comment by erwindon** [comment]
acknowledged!

**Comment by erwindon** [comment]
analysis:
With the introduction of hightstate output, the minion status became more complicated.
Minions were now marked as failed when their hightstate output says there is at least one failed task, even though there is nothing wrong with the `state.apply' command itself.
In that process, the exitcode+success of a regular job was lost.
Easy fix.
