### ISSUE TITLE
No release-branch

### ISSUE THREAD

**Issue by elipsion** [erwindon/SaltGUI#245]
**Is your feature request related to a problem? Please describe.**
When installing SaltGUI via [git.latest](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.git.html#salt.states.git.latest), I can not reference a `release`-branch.

**Describe the solution you'd like**
A `release`-branch, pointing to the latest release tag.

**Describe alternatives you've considered**
Updating the commit-SHA1-reference manually for each release.

**Comment by erwindon** [comment]
There has never been a release branch.
But there are release tags for individual releases.
(and yes, I forgot to add the tag for 1.16.0, so I just did that now)
Also added the `release` TAG, which I will update every release.

**Comment by erwindon** [comment]
Is this sufficient?

**Comment by elipsion** [comment]
Since tags and branches are more or less equivalent this should work, I think.
