### ISSUE TITLE
Improve state.apply output

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#25]
In commit aad5353, the parameter "result" for function _addHost has effectively been transformed into a string. This is because, in the caller, both JSON.stringify and windows.escape return a string. This then causes _addHost to always take the IF block at the beginning of that function.
When I look at the rest of the "_addHost" code, it seems that it is specialized for results of "state.apply".
When I forced the special representation used there, it shows the results broken down by individual state. This includes red/green colors for failure/success.
Should this behaviour be re-instated?

**Comment by maerteijn** [comment]
Not really sure what you mean here, except that my code breaks something and you have an idea how to fix it :)

**Comment by erwindon** [comment]
OK, doesn't sound like I will be breaking something important with changes in that area. The changes are in a branch named `fixjobs` for which a PR will be issued later.

**Comment by maerteijn** [comment]
@erwindon is this still relevent? I think you fixed this when you created the Output class

**Comment by erwindon** [comment]
yes, I think this is still relevant.
In my opinion, SaltGUI should use the nicer format for historic `state.apply` (and friends) jobs also for the regular output of `state.apply` jobs. This formatting code currently lives in `routes/job.js`.
You might not have never seen that output yet, but the formatter was present in the older SaltGUI.
This formatter presents the output per minion as a series of state-outputs, each coloured according to the outcome.

Here is a sample of one minion with 4 states in its request:

![afbeelding](https://user-images.githubusercontent.com/3663742/46371131-cef75380-c687-11e8-9c34-08d70a4f0f92.png)

**Comment by maerteijn** [comment]
Ok, I agree that `salt.apply` output should use the nicer format options so it's easy to see that a (part of the) state change is not successfully applied.

I like  to see this a bit more integrated in  the "terminal" view we currently have. If you for example look at  this from travis ci: https://travis-ci.org/maerteijn/SaltGUI/builds/436212072

It would be awesome to have a oneline summary (green when ok, red when not ok) of the targeted minion, and when clicking the arrow you would see the details.

**Comment by erwindon** [comment]
This was the original formatting, I did not change it. But I agree with the "terminal" view.
I'll remove the green/red backgrounds, These will be replaced by ✔ (0x2714, green) or ✘ (0x2718, red) at the start of each first line. (note that github shows the emoticon version of 0x2714 here. I'll use the normal character).

The current version of SaltGUI shows all details until you collapse them. But that only works one-by-one. We should introduce a separate action to collapse/show all. Shall I use double-click for that? Then single-click shows/collapses one minion (current functionality). and double-click shows/collapses all minions (new).

**Comment by erwindon** [comment]
new sample output for `state.apply`/`state.highstate` from the commandbox:
```
x1:
✔ jenkins_debug
    host=x1, os=CentOS
    Took 1 milliseconds
✔ salt_debug
    host=x1, os=CentOS
    Took 1 milliseconds
✔ salt_minion
    Package salt-minion is already up-to-date
    Took 4.434 seconds

x2:
✔ jenkins_debug
    host=x2, os=Windows
    Took 0 milliseconds
✘ jenkins_install
    No information found for 'jenkins'.
    Took 13.007 seconds
✔ salt_debug
    host=x2, os=Windows
    Took 0 milliseconds
```
(use imagination for colors: names for minion without failures are green as usual; names for minion with failures are red; checkmark is green, X is red)

or as image (with some hidden info):
![afbeelding](https://user-images.githubusercontent.com/3663742/46573229-7a5b1d80-c992-11e8-96f5-2709c265fa9b.png)

**Comment by erwindon** [comment]
I intend to produce 3 PRs from this issue:
1) introduce the formatter for highstate output in commandbox
2) introduce collapse/expand on (multiline) output in commandbox (initially expanded)
3) apply the formatter from the commandbox also to the jobs (where output will be initially collapsed)

**Comment by erwindon** [comment]
Fixed display of changes, they were accidentally not shown
```
hostname123:
✔ jenkins_install
    The following packages were successfully installed/upgraded: jenkins
    changes: {"jenkins": {"new": "2.145-1.1", "old": "2.144-1.1"}}
    Took 56.844 seconds
```

**Comment by erwindon** [comment]
Improved the display of changes:
```
hostname123:
✔ jenkins_install
    The following packages were successfully installed/upgraded: jenkins
    jenkins: "2.144-1.1" ► "2.145-1.1"
    Took 56.844 seconds
```

**Comment by erwindon** [comment]
Improved the title line per task. So the user does not need to search for the statefile where the state is defined:
```
hostname123:
✔ jenkins_debug (from sls/jenkins.sls)
    host=hostname123, os=CentOS
    Took 1 milliseconds
```

**Comment by erwindon** [comment]
Built prototype for collapsing items; and for "all" items:
'''
6 responses ▽
autobuild-it: ▷
autobuild-it-4090: ▽
[
  1
]
autobuild-it-4091: ▽
[
  1
]
'''

**Comment by erwindon** [comment]
All 3 sub-goals reached, closing...
