### ISSUE TITLE
Minor issue - Missing OpenBSD image

### ISSUE THREAD

**Issue by hbonath** [erwindon/SaltGUI#262]
Just a quick heads-up, I am testing out SaltGUI and have a good number of OpenBSD Minions. 
Although you link to an image: os-openbsd.png there is none available.

**Comment by erwindon** [comment]
The image name is generated from the GRAINS information about the system. I once scanned the SALT source code for all possible names that can be returned. Guess I missed openbsd there. The image is now uploaded. THX for reporting!

**Comment by erwindon** [comment]
![os-openbsd](https://user-images.githubusercontent.com/3663742/64562743-e639c900-d34d-11e9-8b44-874c3904e774.png)
