### ISSUE TITLE
Windows minions not reliably displaying status

### ISSUE THREAD

**Issue by hbonath** [erwindon/SaltGUI#263]
I have been noticing that Windows minions are not reliably showing up as online even when they are.

I have made adjustments to my minion config for Windows minions and set "grains_cache: True"
I also adjusted /etc/salt/master and set "gather_job_timeout: 30" 

Upon changing those things are more consistent but from time to time I do have Windows minions that show as offline despite them being up and test.ping-able.

I believe this could simply be a salt issue related to: https://github.com/saltstack/salt/issues/48882 but wanted to bring it to your attention.

**Comment by erwindon** [comment]
yes, I have also seen that Windows minions are a bit unreliable in their response.
What do you suggest to change in SaltGUI?
The code? if so, how?
The documentation? if so, how?
Anything else we should do?

**Comment by hbonath** [comment]
I am not sure about the approach to solving, I was suggesting that it *could* be an issue with salt itself, as many of my Windows minions will time out at the CLI unless I specify a longer timeout value. 

How are you pulling status in SaltGUI? Are you utilizing something like "salt-run manage.status"
If the issue is with salt itself, I would suggest that we update the documentation and note my workarounds in /etc/salt/master and /etc/salt/minion.

**Comment by erwindon** [comment]
SaltGUI is using the salt-api only. Under the hood, that is what `salt`, `salt-key` and `salt-run` also use.

To determine the online status a simple `grains.items` is fired. Similar to `salt '*' grains.items`. This gives us both the online-status and the operating system details at the same time.  On screens other than the main window, another command may be used for that. e.g. on the Keys page, the function `wheel.key.list_all` is used.

SaltGUI is a GUI only, without an installation procedure. We cannot update `/etc/salt/master` or any of the `/etc/salt/minion` files. So the only possibility is a note in our documentation file `README.md`.

**Comment by erwindon** [comment]
I've decided not to document behaviours of SaltStack on Windows in SaltGUI. There are too many differences in installations and versions. The proposed settings also make waiting time longer when a minion is really unreachable, so I cannot recommend these universally.
