### ISSUE TITLE
document additional use cases

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#266]
**Is your feature request related to a problem? Please describe.**
Documentation regarding the use of SaltGUI with commands from `salt-run` and `salt-call` are missing from the documentation.

**Describe the solution you'd like**
Add this documentation. explain prefix `runners.` and `wheel.`

**Describe alternatives you've considered**
Leave the users guessing.

**Comment by erwindon** [comment]
@gnouts 
I've added a paragraph about the command-box. Including the special cases for RUNNERS and WHEEL. Do you thing that it is sufficient?

**Comment by gnouts** [comment]
Yep, it looks good :)

**Comment by erwindon** [comment]
ok, we'll keep it! thx!
