### ISSUE TITLE
Missing closing bracket in Job.js on line 338

### ISSUE THREAD

**Issue by philrenwick** [erwindon/SaltGUI#296]
**Describe the bug**
There is a missing closing bracket in line 338 of static/scripts/routes/Job.js

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to SaltGui website
2. Only top menu is shown
3. Browser console reports error regarding missing bracket

**Expected behaviour**
The login screen should be displayed

**Additional context**
Adding closing bracket fixes the problem and the application works as expected:

-    summaryJobsActiveSpan.insertBefore(Utils.createJobStatusSpan(pJobId, summaryJobsActiveSpan.firstChild);
+   summaryJobsActiveSpan.insertBefore(Utils.createJobStatusSpan(pJobId, summaryJobsActiveSpan.firstChild));

**Comment by erwindon** [comment]
Thanks for reporting! guess I goofed during the latest release...

**Comment by erwindon** [comment]
The release was fine. It was the clean-up that I did just after that.

**Comment by erwindon** [comment]
btw:
"createJobStatusSpan" has 1 parameter, "insertBefore" has 2 parameters. So the missing ")" was just before the ",".
your solution got the application working again but with a small layout issue.

**Comment by erwindon** [comment]
Actually there was one more typo, but that resulted in a functional issue on one page only (the job-details page)
It think all is fixed now. I'll squash the 2 fixes so that everything looks nice again.
the original commit was c80296ce5a457fa89550775d7f03ccb62a5e3ce3
