### ISSUE TITLE
Improve SaltGUI (security) exception handling and improve documentation

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#30]
The current version of SaltGUI states that you should add the following permissions:
`.*` --> all api calls that can be send to minions
`@wheel` --> to allow access to all wheel modules
`@runner` --> to allow access to all runner modules
`@jobs` --> to allow access to the jobs runner and/or wheel module
(see also https://docs.saltstack.com/en/latest/topics/eauth/index.html)
These are basically all possible permissions.

A system administrator may not want to allow all commands to be issued by all users.
e.g. allow all commands to existing minions, except key management (i.e. not all of `@wheel`).

Permission restrictions exist in the Salt system in several dimensions:
- to execute specific commands only
- to execute commands to specific minions only
- to execute commands with specific parameters only

The actual question is: Should SaltGUI support partial permissions?
And if so, what type of restrictions should be supported?

Note that the current version of SaltGUI assumes a session-timeout when it hits a 401 error. It then redirects to the login page. When the permissions are no longer universal, that mechanism must be tuned also.

**Comment by maerteijn** [comment]
My two cents for now:

I think SaltGUI should support partial permissions as in: it should show the user something is not allowed / prohibited with a clear message and hints to know what is going on.

Doing something like adapting the UI based on the permissions would be something I would avoid at this stage as it can become (unnecessary) complicated (maybe the job history list as the only exception).

So redirecting to the login page on all 401 errors should be something to address if this is really the case (also with running command output etc?)

**Comment by erwindon** [comment]
OK, no conflict here with our ideas.
I've already setup an experimental branch `permissions`. Currently this one just substitutes the responses on (any) failure with a structurally valid empty response. That already prevents most of the technical problems, like variable `jobsLoaded` never becoming `true`. 
Obviously this branch must also be updated with any new functionality that is introduced from other branches. This will be a low-priority feature.

**Comment by erwindon** [comment]
The bits of code that I collected in my experimental branch `permissons` is present in a similar form in your branch `api-cleanup-error-handling`. I'll see how much of my branch remains useful.

**Comment by maerteijn** [comment]
I moved my comment from the other ticker to here:

I've been working on some refactoring and error handling sot SaltGUI anticipates on when you disable some permissions or features (like wheels / runners or certain commands).

It's a work in progress (I need to fix some rough edges), but you can see it here: https://github.com/maerteijn/SaltGUI/compare/api-cleanup-error-handling?expand=1

The minimum configuration now required is:
```
external_auth:
  pam:
    salt:
      - grains.items
      - sys.doc
      - state.apply
```
This works out pretty well. I also splitted the api into a real api class and a commandbox class, and did some refactoring.

This is also solving the things discussed in #30 

I'll work on this the following days, add documentation and then I'll send you a pull request. Then I will respond to all the other features you want to add: I think having error handling and permissions straight is something really important now.

**Comment by maerteijn** [comment]
See the pull request #64

**Comment by maerteijn** [comment]
#64 is merged so closing this issue
