### ISSUE TITLE
Support """..""" or some other delimiters in commands for easier parameter passing

### ISSUE THREAD

**Issue by jfunnell** [erwindon/SaltGUI#301]
As an administrator of a fairly complex legacy system, my team and I need to run a fair amount of ad-hoc scripts via SaltGUI that often run into quoting issues, often caused by powershell+windows paths, in embedded scripts.

If SaltGUI supported one (or more) alternative sets of literal quoting delimiters, such as `"""`, `{{ .. }}` or similar it would greatly for running complicated command parameters.

A simple use case would look something like: 
`cmd.run "G@os:windows" """.\audit.ps1 C:\test\""" shell=powershell cwd="""D:\software\tools"""`

**Comment by jfunnell** [comment]
Ah and to further clarify, I wouldn't expect backslashes to escape anything inside a literal-string.. Not even the closing delimiter. Though that is shown in the test case

**Comment by erwindon** [comment]
`"""` is a good choice as I do not see any new problems coming from that. And it is well known in the PY world.

Which existing language uses `{{`? When it is well-known, it is also a candidate. It is certainly easier to type.

Note that `"""` (or any other alternative) can only be a toplevel object/string. do not expect `["a",2,"""C:\test""",4,5]` to work.

**Comment by jfunnell** [comment]
`{{` is used by jinja, the template engine salt uses, though it has a different meaning I guess.
I might also suggest a pre-delimited string, such as q"", where the quote marks can be any character. That way the user can select the appropriate delimiter for the command, and it's not too difficult to parse.

I'm absolutely fine with that caveat by the way, it makes perfect sense to me.

**Comment by erwindon** [comment]
`{{` is ruled out because it is not a string notation in any language.
`q""` is a nasty one, because it rules out any identifier that starts with `q`, and that will break too much regular use (quiet=true, query=..., etc.). 

A prototype for `"""` is now available in branch `superstring`.
This does not have the online-documentation feature; so some documentation must be extended after the 2 feature-branches (this one and the one for #298) come together.

**Comment by erwindon** [comment]
on `q""`: https://en.wikipedia.org/wiki/String_literal#Declarative_notation provides some alternatives with less side-effects.

**Comment by erwindon** [comment]
TODO:
- online documentation (see #298)
- unit tests

**Comment by jfunnell** [comment]
Ah yeah, `q()` doesn't work in a shell-like language. My bad. I think triple-quotes is good enough, and if someone runs into an issue it could be revisited.

Thanks for your quick feedback on all this. Very appreciated.

**Comment by erwindon** [comment]
I'll add the unit-tests and then merge it to master.
That may be tomorrow or so.

**Comment by erwindon** [comment]
done. online documentation will be part of #298
