### ISSUE TITLE
Use of replaceAll needs a polyfill, or alternative method

### ISSUE THREAD

**Issue by Timbus** [erwindon/SaltGUI#303]
**Describe the bug**
It looks like `replaceAll` was only introduced very recently for a few browsers: https://caniuse.com/#search=replaceAll 
Causing all the others to crash when trying to run a command.

**To Reproduce**
Open site in chromium
Trigger a call to CommandBox's `_onRun`

Sorry I didn't pick up on this when I looked at your branch, since I use firefox it didn't affect me, but it will affect a large amount of users.

**Comment by erwindon** [comment]
this was introduced in #297 on Aug 15
I did not spot it on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll, my bad.
solutions:
1) rewrite (e.g. using loop) to avoid the problem
2) use e.g. https://www.npmjs.com/package/core-js
3) make the code optional (e.g. with exception handler)
4) just use string.replace as there is no need to use replaceAll anyway
obviously nr 4 is the solution.

**Comment by erwindon** [comment]
@Timbus 
thanks for reporting!
I will take the opportunity to use ESLINT to report about this problem when it occurs (as there might be more).
See https://stackoverflow.com/questions/15702796/scan-javascript-for-browser-compatibility.

**Comment by erwindon** [comment]
The answer is:
```
/home/erwindon/SaltGUI/saltgui/static/scripts/Api.js
  233:12  error  fetch is not supported in op_mini all, IE 11    compat/compat
  286:20  error  EventSource is not supported in IE 11, Edge 18  compat/compat
```
#304 and #305 added

**Comment by erwindon** [comment]
Note that the `replaceAll` problem is not reported when it is re-introduced.
That is true even when all browser are selected (e.g. FF2).
probably due to the use of polyfill by some other plugins?
suggestions welcome, but for now no further action planned.

**Comment by Timbus** [comment]
Woah, so fast.
Very strange it's not picked up by the linter, I guess it's not a perfect safety net, but still better than nothing for sure.

Thanks so much!
