### ISSUE TITLE
watch salt events for state changes while job is running

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#314]
**Is your feature request related to a problem? Please describe.**
salt-api does not provide progress information. it returns only the end-result.

**Describe the solution you'd like**
When variable `state_events` is set, progress events are sent for each state that completes. These events should be shown. tag="salt/job/20201105020540728914/prog/ss01/0"

**Describe alternatives you've considered**
do nothing

**Additional context**
Design will be something like:
ss01: ●●●●●
i.e. one row per minion. one 'black-circle' per state. each event updates one 'black-circle'.
since we do not know the number of black-circles on one row, these will increase.

This does not work for regular jobs, as control is only returned after the job has finished. But for async jobs, it should work great.

We'll switch to the new table when we receive the first event.
These events are only generated when `state_events` is `True` in the `/etc/salt/master` file.
From then the table is filled with the summary information for each state. This provides the same information as in the job viewer.
Decided not to view the actual output here, as this is only intended as a progress monitor. The colours and tooltips provide a first impression, but not more.

**Comment by erwindon** [comment]
first prototype available...

regular output for an async job:
![image](https://user-images.githubusercontent.com/3663742/98300837-23353600-1fba-11eb-9410-fc97a6ab5e9e.png)

just started:
![image](https://user-images.githubusercontent.com/3663742/98301125-950d7f80-1fba-11eb-896c-2d4dc57110cc.png)

completed:
![image](https://user-images.githubusercontent.com/3663742/98300976-5972b580-1fba-11eb-9b50-e0e25eb0dd76.png)

**Comment by erwindon** [comment]
@elipsion
FYI
I'm extending SaltGUI to use the same presentation form as the highstate view of jobs, but now with a live view for highstate jobs that are started asynchronously. it shows the real-time progress for each minion for any type of command. but when a highstate is performed and option `state_events` is switched on on the master, then the tasks are also reported in real-time with the well known green/red balls.

**Comment by elipsion** [comment]
Ping, @dunz0r, my successor.

**Comment by erwindon** [comment]
branch 'stateupdates' merged
