### ISSUE TITLE
Please don't rewrite history on master branch

### ISSUE THREAD

**Issue by bbinet** [erwindon/SaltGUI#328]
It seems the history of the master branch has been rewritten and forced pushed a few times recently as `git pull origin master` generate conflict errors.
I think we should avoid force pushing to a remote branch which is public and which other people can be working on.

**Comment by erwindon** [comment]
Bruno,
You are correct and thank you for your involvement.
Force-push is used by me to fix recent spelling errors in commit-text and to add changes that were missed in the previous git-add.
I have several workspaces for this repository for which I always use "pull -r", which effectively hides this problem.
Now that I am (more) aware of this problem for other people, I'll be much more careful about this.
I hope this answers and solves the issue...

**Comment by bbinet** [comment]
Thank you @erwindon
