### ISSUE TITLE
create RPM package for Red Hat Linux 

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#333]
**Is your feature request related to a problem? Please describe.**
Add a procedure to create a RPM package as used by RetHat Linux family.
This allows easier installations.

**Describe the solution you'd like**
Add package descriptor in a new sub-directory "redhat".
provide enough documentation and/or scripts that an actual package can be build

mention "salt-api" as suggestion

**Describe alternatives you've considered**
none (stick to the docker image support)

**Additional context**
This also makes saltgui more visible.

when successful, the package should be added to one or more redhat distributions

see also #332

**Comment by aboe76** [comment]
Too lessen the burden on maintaining repositories and building it might be a good idea to use "obs" this can be integrated with github:
https://kamarada.github.io/en/2019/03/19/integrating-the-open-build-service-with-github/

**Comment by erwindon** [comment]
no further reactions on this one. seems the demand is also low. this will be re-opened when there is new demand
