### ISSUE TITLE
migrate to use a proper web-application framework

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#334]
**Is your feature request related to a problem? Please describe.**
The current version of SaltGUI uses its own simple navigation framework. While it works reasonably well, it has a long list of minor problems:
* it is a lot of extra code to maintain
* the back-button does not always work properly
* page refresh does not always work properly
* the page url is not always correct with the content that is shown
* hidden pages still contribute to the scrollbar length

some of these have their own issue (e.g. #229, #293, #327) but may benefit for a more solid framework

**Describe the solution you'd like**
select a web-application framework with the following properties:
* it must be client-only
* must be fully open/free
* must support a full application, from navigation 
* is popular and/or easy to use
* can still use most of the current styling and flow

The table below lists 9 frameworks as found on https://opensource.com/article/20/5/open-source-javascript-frameworks:
1. ReactJS
2. Angular
3. VueJS
4. MeteorJS
5. KnockoutJS
6. EmberJS
7. BackboneJS
8. Svelte
9. AureliaJS

Q: What can YOU do?
A: Point out the ones from this list that are not suitable for whatever reason, so that in the end we have a best choice!

**Comment by bbinet** [comment]
So you would like to rewrite everything from scratch using one of these js frameworks? Sounds like quite a bit of work! ;-)
If this is just an issue with the router, why not try to only pick a router component like the following:
https://github.com/ChrisRu/es6-router
(I don't have any experience with it, I've just searched for a pure js router)

**Comment by erwindon** [comment]
The router has the most actual problems.
But the gui itself has too much code, mostly in the lower layers of html object manipulation. so improvement there is welcome too.

part of the investigation would have been on how many changes are needed in the existing system.

saltgui already has a single page navigation facility. but I broke it 2 years ago with the first new feature (the keys page) that I supplied. I never realized that single page navigation was in place as saltgui at that time did not have additional pages anyway. and all this time we had this router doing basically nothing. this continued with all new pages. decision was between fixing and replacing (this issue). I was also investigating to fix the current router and it seems not too difficult. So I'll do that in parallel.

**Comment by erwindon** [comment]
The tests with the refurbished (current) router are very promising.
We might not need to push the software into a standard framework.

**Comment by bbinet** [comment]
That's great! 👏

**Comment by erwindon** [comment]
#339 is a better direction
