### ISSUE TITLE
Add support for SaltGUI configuration through javascript in config.js

### ISSUE THREAD

**Issue by bbinet** [erwindon/SaltGUI#337]
**Is your feature request related to a problem? Please describe.**
For now most of SaltGUI configuration is done on the salt-master: this may be problematic if a user is not allowed to execute wheel function "config.values" as he won't be able to retrieve SaltGUI configuration.

**Describe the solution you'd like**
As there is already a `config.js` file for salt-api configuration, we could extend its usage so that we can also configure default values for SaltGUI configuration, so that if the wheel function "config.values" is not allowed, we can still configure SaltGUI from this config.js file.

**Comment by erwindon** [comment]
`config.js` also comes from the server. but a setup in which you can control saltgui, but not master, is a known one.
btw, this sheds a whole new light on the "local-templates" feature.
when you generalize this, there are 3 config locations: "master", "saltapi/saltgui" and "browser-local".
it also opens the issue of option inheritance. i.e. for simple settings, the locations should be used in reverse order. but for options that are a list, it may be reasonable to let the options combine.
I'll let this one rest a bit while I'm working on other requests...

**Comment by bbinet** [comment]
So local-storage config would take priority over config.js config, which would also take priority over salt-master config, right?

**Comment by erwindon** [comment]
sorry, that took unusually long...
similar questions have not popped up. so I doubt that this is a problem for many.
a solution would make the application more complex.
my decision is to close the request for this idea.
feel free to ask for re-open, suggest alternatives, etc.
