### ISSUE TITLE
Schedule job needs to have the <name> between "quotes" or it'll fail on a space

### ISSUE THREAD

**Issue by xzenor** [erwindon/SaltGUI#366]
**Describe the bug**
When adding/removing/modifying a schedule the name needs to be in quotes when there's a space in it. This is especially annoying when you try to modify an existing schedule with a space in the name.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure to have a schedule with a space in the name
2. Try to modify it with SaltGUI
3. Run Command (no need to actually change anything)

**Expected behaviour**
The name should have quotes around it by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/15305998/127670003-b9ee04a5-1cc1-495f-a443-4d11ec971c13.png)

**Comment by erwindon** [comment]
@xzenor 
thanks for reporting!
I repeated it and confirm the effect (not that I doubted your report!)
I will take the opportunity to verify all other cases where a command is constructed, and I'll likely put a little framework in place that automatically adds the quotes as needed...

**Comment by erwindon** [comment]
I've created a fix for this.
when generating a command, quotes are now always added when an argument is not a trivial string.
the proposed version is on branch "quotednames".
I tested all commands for schedules on a schedule with a space in its name (modify/enable/disable/delete/run). Also regression tested with most of the other commands in SaltGUI.
can you please do a quick test as well using that branch?

**Comment by xzenor** [comment]
Wow... I was NOT expecting a response and even a fix this fast!  

I'd be happy to give it a try! I'm gonna have to figure out how to change branches first but I'm sure that's documented somewhere.  

I'll let you know!

**Comment by xzenor** [comment]
I'm probably just a n00b.. But _git pull origin quotednames_ didn't fix anything for me.. Still no quotes

**Comment by erwindon** [comment]
sorry! it seems that I did not actually commit the source code... :-(
but I did not forget to push the code so the branch was still equal to master...
this is of course fixed now.

also: not sure whether that git command is doing the right thing.
i think `git checkout quotednames` is better (after the usual `git fetch` to make new branches known locally)

**Comment by xzenor** [comment]
There I was, cursing at myself that I should really dive into git a bit more because I couldn't even figure out how to switch branches :-D
Anyway, tried my previous command first to see if it would work now. and it did.
Works like a charm now! Thanks!

**Comment by erwindon** [comment]
> Works like a charm now!
I'll merge the code tomorrow.
This is also a good excuse to push out a new release number, so I'll do that too.

would you like to "star" this project? (in the top-right of the page) I don't normally ask for this, but '300' looks so much nicer...

**Comment by xzenor** [comment]
There.. 300 now. I would've thought it'd be more though. SaltGUI is like, the only GUI for Salt that's worth mentioning (next to Alcali but I never got that to work).

**Comment by erwindon** [comment]
thx for the compliment, thx @oliverdunk and @maerteijn for starting and maintaining this project before me.
See https://github.com/hbokh/awesome-saltstack#tools for other tools.
Also do not forget the enterprise edition of Salt, which comes with a gui.
