### ISSUE TITLE
Spontaneous logout after /stats returned http error 500

### ISSUE THREAD

**Issue by pckroon** [erwindon/SaltGUI#386]
**Describe the bug**
I get spontaneously logged out from saltgui after a seemingly arbitrary amount of time. It's most reliable when on the 'jobs' tab, and waiting for that to populate.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'jobs' tab
2. Wait for 30-60 seconds
4. Get redirected to `?reason=no-session`

**Expected behaviour**
I expect to not have the session be terminated within 1h.

**Additional context**
Relevant eauth:
```yaml
  pam:
    saltgui:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'
```

rest_cherrypy:
```yaml
rest_cherrypy:
  port: 8080
  host: 192.168.12.56
  debug: False
  ssl_crt: /etc/salt/pki/tls/certs/localhost.crt
  ssl_key: /etc/salt/pki/tls/certs/localhost.key
  log_error_file: /var/log/salt/api.error
  log_access_file: /var/log/salt/api.access
  collect_stats: True
  app: /srv/SaltGUI/saltgui/index.html
  static: /srv/SaltGUI/saltgui/static
  static_path: /static
```

Saltgui options:
```
saltgui_output_formats: highstate,yaml
saltgui_datetime_fraction_digits: 0
saltgui_preview_grains:
  - "osrelease_info"
  - "$.ipv4[-1]"
```

I get the following lines in my log when it triggers:
```
Oct 12 11:39:05 salt salt-api[1247748]: 192.168.2.1 - - [12/Oct/2021:11:39:05] "GET /stats HTTP/1.1" 500 956 "https://192.168.12.56:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
Oct 12 11:39:05 salt salt-api[1247748]: 192.168.2.1 - - [12/Oct/2021:11:39:05] "POST /logout HTTP/1.1" 200 41 "https://192.168.12.56:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
Oct 12 11:39:06 salt salt-api[1247748]: 192.168.2.1 - - [12/Oct/2021:11:39:06] "POST / HTTP/1.1" 401 675 "https://192.168.12.56:8080/?reason=no-session" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
```

**Comment by erwindon** [comment]
@pckroon 
Thanks for the report and also thanks for solving the problem, as I would not have a clue where to start looking for a problem...

Still, I am curious in the real problem behind this. This may need improvement in SaltStack itself, or it may need some documentation in SaltGUI, or maybe there is even a workaround possible in SaltGUI.

In the "To reproduce", you mention "go to Jobs". That page has a timer/background-based helpers to show the status+details of the visible jobs. could you already see the list of jobs? were some "details" already filled in? was the "status" column already filled in?

**Comment by erwindon** [comment]
additionally to the 2 background/timer processes, indeed the `/stats` is used to verify the connection. I now see that `/stats` returned HTTP error code 500. I'll see whether I can update SaltGUI to be more selective in how it responds to errors from `/stats`. I'll use this ticket for that.

**Comment by erwindon** [comment]
ok, I was using the development version, which is slightly ahead of that, that also explains why I get a slightly different error visible. but the effect is the same: logout.

**Comment by erwindon** [comment]
you solved your end of the problem. I investigated enhancements, but found none.
no more work left for this issue.
