### ISSUE TITLE
No job information about executed schedules

### ISSUE THREAD

**Issue by achimmihca** [erwindon/SaltGUI#394]
**Describe the bug**
I am not sure if this is a bug. Maybe I am looking in the wrong place?

When viewing the jobs of a minion, I don't see any information about executed schedules.
For example, I have a schedule in a pillar:

```
schedule:
  echo-hello:
    seconds: 60
    function: state.apply
    args:
      - echo-hello
```

echo-hello.sls appends a string to some file via `echo "hello" >> C:\hello.txt`

I see that the schedule is executed because the text is added to the file every 60 seconds.
I also see the schedule in SaltGUI.
But I don't see any information about executions of this schedule in SaltGUI.

Is it not possible to view jobs run from schedule?
I also don't see any information about executed schedules in the SaltStack logs. Maybe it is a SaltStack issue?

Are scheduled jobs handled differently somehow?

**To Reproduce**
1. Setup a schedule as above
2. Check that the schedule is executed (by affected files)
3. Try to find information about the executed schedule in SaltGUI. You won't find any

**Expected behaviour**
The job executed from schedule is listed on the Jobs tab in SaltGUI, just like the state would have been executed from command line.

**Comment by erwindon** [comment]
@achimmihca
With a simpler setup (just test.ping or state.apply on existing states, in a schedule), I can see those jobs.
The Jobs page (and the jobs panels) by default apply a filter to skip trivial jobs, these are mostly the jobs that were initiated by the SaltGUI application itself.
On the Jobs page (but not on the jobs panels) you can select "Show all jobs".
Does that make the jobs visible?
If so, what is the value in column "Function"?

(aside: found https://github.com/erwindon/SaltGUI/issues/395 while testing this)

**Comment by achimmihca** [comment]
Thanks for the quick reply! 

You are right I now see the jobs normally.
Not sure what was wrong.

I was unaware of "show all jobs" option. thanks for the hint.
