### ISSUE TITLE
Using logon with 'file' shows credentials in the list

### ISSUE THREAD

**Issue by reiner1959-coder** [erwindon/SaltGUI#397]
I implemented the file logon for our servers. The problem there was the selection list shows the content of the file containing username and passwd. 
I commented the lines reading the txt file in file: Scripts/Login.js line 123 - 125.

**Comment by erwindon** [comment]
@reiner1959-coder 
the file `salt-auth.txt` is **not** intended to contain any credentials.
it should only be used to contain the name of login **methods**.
the list of names can be found on https://docs.saltproject.io/en/latest/ref/auth/all/index.html
when you want to support the "file" method, then the only text in that file is the word `file`.
the actual configuration is (as usual) in the file `master` on the salt server (which in this case then points to a server-based file).

**Comment by reiner1959-coder** [comment]
Thanks for clarify that. I tested it and it works.
