### ISSUE TITLE
Highstate conformity

### ISSUE THREAD

**Issue by xzenor** [erwindon/SaltGUI#401]
**Is your feature request related to a problem? Please describe.**
NO. Just a nice to have. No problem and no rush.
A cool feature Alcali provides is to see in 1 view which server is conform with highstate. 

**Describe the solution you'd like**
The ability to see in simple overview which server conforms with highstate and which does not.
Alcali does this and it's a quick way to see if any of the servers are acting up and having state problems.
It does this by running `state.highstate test=True` and searching for `result != True`
It would be nice to have. Could even be implemented in the minios overview maybe 
Here's the alcali link: https://alcali.dev/views/conformity/

**Describe alternatives you've considered**
I can run the command but it won't provide a simple output. I'll have to scroll through everything and check for red or yellow text but that's not very efficient. 

**Additional context**
![alcali screenshot](https://alcali.dev/images/conformity_view.png)

**Comment by erwindon** [comment]
@xzenor
`state.highstate test=True` is available from the drop-down menu on the main screen.
And you can collapse the output so that a colourful summary is shown. But, indeed it is not directly available.
That summary is also available when you choose a job from the Jobs page. But then you need to find the jobs in the list first.
e.g.
![afbeelding](https://user-images.githubusercontent.com/3663742/142456537-dea628c1-b533-4ddc-946c-d1cce983c59f.png)

Alcali achieves this functionality by accessing a database. But SaltGUI does not have a database with job results and/or events. The alternative would be a search through all jobs of type "state.apply" in the jobs list. An separate API call is required to retrieve the details of each job. You can see the consequences when you are on the Jobs page, where the Details column is retrieved asynchronously and sequentially. Introducing an application-level database is beyond the design goals of SaltGUI.
I have thought of adding a page with this functionality earlier, but then dropped the idea for that same reason.
At that time, SaltGUI was not using using screens with asynchronous functionality. That has changed, so something can be done.

proposal:
* new page "Highstate" under menu button "Jobs"
* the main panel of the page would hold a list of Minions
* under the hood, the screen would retrieve the jobs list, filtered by command "state.apply"
* timer logic will retrieve one jobs at a time, just like the Jobs page
* when the job holds information for minions for which we have no state information yet, it will be used to populate the corresponding row; this always only the latest minion info is shown. this may become a bit confusing if someone executed a state.apply for a single state only.
* when all rows are populated, the timer-loop can stop
* when 10 jobs are inspected, the timer-loop should stop to reduce server load.
* the per-minion task-summary will again have the same format as before, see screen-print above

each row essentially is a "job" row, so the columns JID/Target/Function/StartTime can be shown again.
The Status/Details columns will be replaced by the task-summary.
the JID is usually the same for many/all jobs.

**Comment by xzenor** [comment]
So what if you've never run state.highstate before and it is therefore not in the job history?

**Comment by erwindon** [comment]
the loop would end quickly and for each minion the text "not found" (or something similar) will be shown.
The text should be consistent with the fact that the jobs database typically only holds one day of data, so the a text like "has never run" is inappropriate.

**Comment by erwindon** [comment]
one open question is on how to handle the state.apply jobs.
my idea is to not look at the arguments at all.
so a "state.apply test=True" is as valid as "state.apply" or any other variation.

**Comment by erwindon** [comment]
a first version will be present on branch "highstatepage".

first some visuals...

the new page:
![afbeelding](https://user-images.githubusercontent.com/3663742/142626674-d86e6517-b954-4c54-a18f-87c6bbac20a8.png)

placement in the main menu:
![afbeelding](https://user-images.githubusercontent.com/3663742/142626774-4d4e8a38-8d75-49a6-b739-3f1168e62002.png)

panel level dropdown menu:
![afbeelding](https://user-images.githubusercontent.com/3663742/142626838-5227f804-0523-4bba-82fc-dad35d784c96.png)

per-minion dropdown menu, state.apply command was found:
![afbeelding](https://user-images.githubusercontent.com/3663742/142627292-051e28f9-39d8-4aee-9e0f-04b9dece62cb.png)

per-minion dropdown menu, no state.apply command was found:
![afbeelding](https://user-images.githubusercontent.com/3663742/142627349-1fd87811-8c90-4ac6-a3b7-5c5cc0a65fb2.png)

tooltip on a task, same as on other screens where tasks are shown:
![afbeelding](https://user-images.githubusercontent.com/3663742/142626941-2f134a1f-444e-43b0-a11b-cc20b25bfc9c.png)

**Comment by erwindon** [comment]
while working on this, I realised that SaltGUI did not have an quick way to re-run an individual state. that is now #402.

the icons use a black background because the original colours were so far only used on a black background and they do not look good on a white background.

the performance is actually very acceptable when the first `state.apply` job is for all minions. SaltGUI will now inspect up to 10 `state.apply` jobs to find all minions. these are fired at an interval of 1 second. so it will take 10 to 15 seconds before the "no job" conclusion is shown; or faster when there are less than 10 `state.apply` jobs in the database anyway.

**Comment by xzenor** [comment]
That looks awesome!

**Comment by erwindon** [comment]
I just pushed the changes on the branch `highstatepage`.
Can you give it a try?
Please keep an eye on the webbrowser-console for unusual output...

**Comment by erwindon** [comment]
just added a few items to make it more useable:
* when using "show details", the output is scrolled to the relevant minion
* when more than 50 minions in a job output, all output is collapsed. made an exception for the above case
* clicking on a state summary (a coloured ball) proposes the `state.sls_id` command to fix the issue. note that the screen is not updated until the next `state.apply test=true`.

**Comment by xzenor** [comment]
Apparently pJob is undefined..
```
Uncaught TypeError: pJob is undefined
    _handleJob https://salmaster.REDACTED:3333/static/scripts/panels/HighState.js:151
    _updateNextJob https://salmaster.REDACTED:3333/static/scripts/panels/HighState.js:143
    _updateNextJob https://salmaster.REDACTED:3333/static/scripts/panels/HighState.js:146
    setTimeout handler*_updateNextJob https://salmaster.REDACTED:3333/static/scripts/panels/HighState.js:145
    _handleHighstateRunnerJobsListJobs https://salmaster.REDACTED:3333/static/scripts/panels/HighState.js:123
    onShow https://salmaster.REDACTED:3333/static/scripts/panels/HighState.js:36
    promise callback*onShow/< https://salmaster.REDACTED:3333/static/scripts/panels/HighState.js:35
    promise callback*onShow https://salmaster.REDACTED:3333/static/scripts/panels/HighState.js:33
    onShow https://salmaster.REDACTED:3333/static/scripts/pages/Page.js:175
    _showPage https://salmaster.REDACTED:3333/static/scripts/Router.js:360
    goTo https://salmaster.REDACTED:3333/static/scripts/Router.js:319
    _registerMenuItem https://salmaster.REDACTED:3333/static/scripts/Router.js:115
    _registerMenuItem https://salmaster.REDACTED:3333/static/scripts/Router.js:111
    _registerRouterEventListeners https://salmaster.REDACTED:3333/static/scripts/Router.js:150
    Router https://salmaster.REDACTED:3333/static/scripts/Router.js:58
    <anonymous> https://salmaster.REDACTED:3333/static/scripts/index.js:5
    EventListener.handleEvent* https://salmaster.REDACTED:3333/static/scripts/index.js:5
```

I'm also not getting any colors.
![image](https://user-images.githubusercontent.com/15305998/142755536-0c3738b1-bb99-4ce2-87ca-98515f0b42b7.png)
The mouseovers so work though..

**Comment by erwindon** [comment]
the colours may be missing due to caching, which is usually more aggressive for css files. can you do a shift-refresh? (at least in Firefox, shift-refresh invalidates the file-cache before doing the actual refresh). the latest version has had some minor css changes that are also not visible.

the `pJob is undefined` does not occur here. would it be possible to show the following JSON responses from the API functions that the screen uses?
* from `jobs.list_jobs` with `search_function` set to `state.apply` (the jobs side panel fires another instance of it without that parameter); and
* from all `jobs.list_job` that were executed after that.

did you use the classic job-store, or the MySQL job-store?

btw, while testing this, I found a problem when showing the result from `state.apply` where errors were returned, e.g. due to a non-existing sls file. the part with the error messages was used (wrong) and the summary failed (secondary, but also wrong).
also the quotes around the parameters should have been avoided. I probably missed a use-case.

**Comment by xzenor** [comment]
You were right about the colors. They're there after a refresh.
I'm a bit confused what you want me to provide.. I ran this on the commandline but the result isn't really useful I think..
```
# salt-run jobs.list_jobs search_function=state.apply --out=json
{
    "20211119225947991233": {
        "Function": "state.apply",
        "Arguments": [
            "up2date"
        ],
        "Target": "*",
        "Target-type": "glob",
        "User": "USERNAME",
        "StartTime": "2021, Nov 19 22:59:47.991233",
        "EndTime": "2021, Nov 19 23:01:13.502820"
    }
}
```

**Comment by erwindon** [comment]
I meant the API log that the browser maintains. e.g. in Firefox: `More tools` --> `Web Developer Tools` --> tab `Network`.
But since it is the same output, I'm very happy with this.
Can you do `salt-run jobs.list_job 20211119225947991233 --out=json` too?

**Comment by xzenor** [comment]
Sure thing

```
# salt-run jobs.list_job 20211119225947991233 --out=json
{
    "jid": "20211119225947991233",
    "Error": "Cannot contact returner or no job with this jid",
    "StartTime": "2021, Nov 19 22:59:47.991233",
    "Result": {}
}
```

Right now I'm not getting any result anymore.. I didn't change anything so this is really weird. I've shift-refreshed already. Even rebooted everything but all I see now is this:

![image](https://user-images.githubusercontent.com/15305998/142760677-aa7b27e5-41d5-4c6e-8ca8-c1fc5fac30e8.png)

**Comment by erwindon** [comment]
that job is now more that 24 hours old, probably got erased from the jobstore after the standard retention time

**Comment by xzenor** [comment]
ah yes.. I've not run a state.apply.. I have an hourly scheduled state.highstate. 
I'll run a state.apply and provide the output.

btw, why not use the state.highstate?

**Comment by xzenor** [comment]
```json
# salt-run jobs.list_jobs search_function=state.apply --out=json
{
    "20211121120011941540": {
        "Function": "state.apply",
        "Arguments": [
            "up2date"
        ],
        "Target": "*",
        "Target-type": "glob",
        "User": "USERNAME",
        "StartTime": "2021, Nov 21 12:00:11.941540",
        "EndTime": "2021, Nov 21 12:00:58.132349"
    }
}
```

```json
# salt-run jobs.list_job 20211121120011941540 --out=json
{
    "jid": "20211121120011941540",
    "Function": "state.apply",
    "Arguments": [
        "up2date"
    ],
    "Target": "*",
    "Target-type": "glob",
    "User": "USERNAME",
    "Minions": [
        "AAAA",
        "BBBB",
        "CCCC",
        "DDDD",
        "EEEE",
        "FFFF",
        "GGGG",
        "HHHH"
    ],
    "StartTime": "2021, Nov 21 12:00:11.941540",
    "Result": {
        "AAAA": {
            "return": {
                "module_|-Update packages refresh db_|-pkg.refresh_db_|-run": {
                    "name": "pkg.refresh_db",
                    "changes": {
                        "ret": {
                            "total": 5,
                            "success": 5,
                            "failed": 0
                        }
                    },
                    "comment": "Module function pkg.refresh_db executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 0,
                    "start_time": "13:00:12.594199",
                    "duration": 356.615,
                    "__id__": "Update packages refresh db"
                },
                "module_|-Update packages install updates_|-pkg.upgrade_|-run": {
                    "name": "pkg.upgrade",
                    "changes": {
                        "ret": {}
                    },
                    "comment": "Module function pkg.upgrade executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 1,
                    "start_time": "13:00:12.951835",
                    "duration": 1.016,
                    "__id__": "Update packages install updates"
                }
            },
            "retcode": 0,
            "success": true,
            "out": "highstate"
        },
        "FFFF": {
            "return": {
                "module_|-Update packages refresh db_|-pkg.refresh_db_|-run": {
                    "name": "pkg.refresh_db",
                    "changes": {
                        "ret": null
                    },
                    "comment": "Module function pkg.refresh_db executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 0,
                    "start_time": "07:00:12.610427",
                    "duration": 2050.677,
                    "__id__": "Update packages refresh db"
                },
                "module_|-Update packages install updates_|-pkg.upgrade_|-run": {
                    "name": "pkg.upgrade",
                    "changes": {
                        "ret": {}
                    },
                    "comment": "Module function pkg.upgrade executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 1,
                    "start_time": "07:00:14.661485",
                    "duration": 5371.988,
                    "__id__": "Update packages install updates"
                }
            },
            "retcode": 0,
            "success": true,
            "out": "highstate"
        },
        "BBBB": {
            "return": {
                "module_|-FreeBSD updates fetch_|-freebsd_update.fetch_|-run": {
                    "name": "freebsd_update.fetch",
                    "changes": {
                        "ret": "Looking up update.FreeBSD.org mirrors... 2 mirrors found.\nFetching metadata signature for 13.0-RELEASE from update2.freebsd.org... done.\nFetching metadata index... done.\nInspecting system... done.\nPreparing to download files... done.\n\nNo updates needed to update system to 13.0-RELEASE-p5."
                    },
                    "comment": "Module function freebsd_update.fetch executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 0,
                    "start_time": "13:00:12.777596",
                    "duration": 22302.752,
                    "__id__": "FreeBSD updates fetch"
                },
                "module_|-FreeBSD updates install_|-freebsd_update.install_|-run": {
                    "name": "freebsd_update.install",
                    "changes": {
                        "ret": "Unable to run \" /usr/sbin/freebsd-update  install\" with run_args=\"None\". Error: No updates are available to install.\nRun '/usr/sbin/freebsd-update fetch' first."
                    },
                    "comment": "Module function freebsd_update.install executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 1,
                    "start_time": "13:00:35.080798",
                    "duration": 104.476,
                    "__id__": "FreeBSD updates install"
                },
                "module_|-Update packages refresh db_|-pkg.refresh_db_|-run": {
                    "name": "pkg.refresh_db",
                    "changes": {
                        "ret": true
                    },
                    "comment": "Module function pkg.refresh_db executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 2,
                    "start_time": "13:00:35.185607",
                    "duration": 525.541,
                    "__id__": "Update packages refresh db"
                },
                "module_|-Update packages install updates_|-pkg.upgrade_|-run": {
                    "name": "pkg.upgrade",
                    "changes": {
                        "ret": {}
                    },
                    "comment": "Module function pkg.upgrade executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 3,
                    "start_time": "13:00:35.711503",
                    "duration": 361.559,
                    "__id__": "Update packages install updates"
                },
                "module_|-autoremove unused dependencies_|-pkg.autoremove_|-run": {
                    "name": "pkg.autoremove",
                    "changes": {
                        "ret": "Checking integrity... done (0 conflicting)\nNothing to do."
                    },
                    "comment": "Module function pkg.autoremove executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 4,
                    "start_time": "13:00:36.073345",
                    "duration": 63.888,
                    "__id__": "autoremove unused dependencies"
                }
            },
            "retcode": 0,
            "success": true,
            "out": "highstate"
        },
        "HHHH": {
            "return": {
                "module_|-FreeBSD updates fetch_|-freebsd_update.fetch_|-run": {
                    "name": "freebsd_update.fetch",
                    "changes": {
                        "ret": "Looking up update.FreeBSD.org mirrors... 2 mirrors found.\nFetching metadata signature for 13.0-RELEASE from update2.freebsd.org... done.\nFetching metadata index... done.\nInspecting system... done.\nPreparing to download files... done.\n\nNo updates needed to update system to 13.0-RELEASE-p5."
                    },
                    "comment": "Module function freebsd_update.fetch executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 0,
                    "start_time": "13:00:12.726991",
                    "duration": 35536.058,
                    "__id__": "FreeBSD updates fetch"
                },
                "module_|-FreeBSD updates install_|-freebsd_update.install_|-run": {
                    "name": "freebsd_update.install",
                    "changes": {
                        "ret": "Unable to run \" /usr/sbin/freebsd-update  install\" with run_args=\"None\". Error: No updates are available to install.\nRun '/usr/sbin/freebsd-update fetch' first."
                    },
                    "comment": "Module function freebsd_update.install executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 1,
                    "start_time": "13:00:48.263432",
                    "duration": 82.412,
                    "__id__": "FreeBSD updates install"
                },
                "module_|-Update packages refresh db_|-pkg.refresh_db_|-run": {
                    "name": "pkg.refresh_db",
                    "changes": {
                        "ret": true
                    },
                    "comment": "Module function pkg.refresh_db executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 2,
                    "start_time": "13:00:48.346165",
                    "duration": 284.235,
                    "__id__": "Update packages refresh db"
                },
                "module_|-Update packages install updates_|-pkg.upgrade_|-run": {
                    "name": "pkg.upgrade",
                    "changes": {
                        "ret": {}
                    },
                    "comment": "Module function pkg.upgrade executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 3,
                    "start_time": "13:00:48.630759",
                    "duration": 341.649,
                    "__id__": "Update packages install updates"
                },
                "module_|-autoremove unused dependencies_|-pkg.autoremove_|-run": {
                    "name": "pkg.autoremove",
                    "changes": {
                        "ret": "Checking integrity... done (0 conflicting)\nNothing to do."
                    },
                    "comment": "Module function pkg.autoremove executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 4,
                    "start_time": "13:00:48.972694",
                    "duration": 50.202,
                    "__id__": "autoremove unused dependencies"
                }
            },
            "retcode": 0,
            "success": true,
            "out": "highstate"
        },
        "GGGG": {
            "return": {
                "module_|-FreeBSD updates fetch_|-freebsd_update.fetch_|-run": {
                    "name": "freebsd_update.fetch",
                    "changes": {
                        "ret": "Looking up update.FreeBSD.org mirrors... 2 mirrors found.\nFetching metadata signature for 13.0-RELEASE from update1.freebsd.org... done.\nFetching metadata index... done.\nInspecting system... done.\nPreparing to download files... done.\n\nNo updates needed to update system to 13.0-RELEASE-p5."
                    },
                    "comment": "Module function freebsd_update.fetch executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 0,
                    "start_time": "13:00:12.952676",
                    "duration": 43151.954,
                    "__id__": "FreeBSD updates fetch"
                },
                "module_|-FreeBSD updates install_|-freebsd_update.install_|-run": {
                    "name": "freebsd_update.install",
                    "changes": {
                        "ret": "Unable to run \" /usr/sbin/freebsd-update  install\" with run_args=\"None\". Error: No updates are available to install.\nRun '/usr/sbin/freebsd-update fetch' first."
                    },
                    "comment": "Module function freebsd_update.install executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 1,
                    "start_time": "13:00:56.105509",
                    "duration": 139.132,
                    "__id__": "FreeBSD updates install"
                },
                "module_|-Update packages refresh db_|-pkg.refresh_db_|-run": {
                    "name": "pkg.refresh_db",
                    "changes": {
                        "ret": true
                    },
                    "comment": "Module function pkg.refresh_db executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 2,
                    "start_time": "13:00:56.245285",
                    "duration": 805.55,
                    "__id__": "Update packages refresh db"
                },
                "module_|-Update packages install updates_|-pkg.upgrade_|-run": {
                    "name": "pkg.upgrade",
                    "changes": {
                        "ret": {}
                    },
                    "comment": "Module function pkg.upgrade executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 3,
                    "start_time": "13:00:57.051182",
                    "duration": 956.734,
                    "__id__": "Update packages install updates"
                },
                "module_|-autoremove unused dependencies_|-pkg.autoremove_|-run": {
                    "name": "pkg.autoremove",
                    "changes": {
                        "ret": "Checking integrity... done (0 conflicting)\nNothing to do."
                    },
                    "comment": "Module function pkg.autoremove executed",
                    "result": true,
                    "__sls__": "up2date",
                    "__run_num__": 4,
                    "start_time": "13:00:58.008191",
                    "duration": 58.024,
                    "__id__": "autoremove unused dependencies"
                }
            },
            "retcode": 0,
            "success": true,
            "out": "highstate"
        }
    },
    "EndTime": "2021, Nov 21 12:00:58.132349"
}
```

**Comment by erwindon** [comment]
thx for the data!

I added code to intercept errors when the state was applied. e.g. with a non-existing sls:
![image](https://user-images.githubusercontent.com/3663742/142761111-649b383c-56f9-45a2-a35f-9cb827614ba1.png)
I think this is more useful than skipping such job for that minion.

> highstate vs apply

that was accidental.
but also, see https://stackoverflow.com/questions/55185684/whats-the-difference-between-state-sls-and-state-apply.
so `state.apply` is just more flexible, maybe that's why I always use that.
but indeed we should not rule out `state.highstate`.

**Comment by xzenor** [comment]
ah you can run state.apply without and arguments. didn't know that.

**Comment by erwindon** [comment]
`state.highstate` jobs are now also selected. luckily that did not need a separate query.

I could not replay the problem with the supplied json on the latest version. hopefully the other changes that were applied solved this also. can you please retry?

**Comment by xzenor** [comment]
I'm not getting the error anymore after the update. 
It looks really good now.

So if I understand this correctly, this checks the job history and gives colored balls based on whether something failed inside that job?

**Comment by erwindon** [comment]
thx for testing!

> So if I understand this correctly, this checks the job history and gives colored balls based on whether something failed inside that job?

yes
I've just added a small help function on the page as a reminder.
since there is only a "jobs" database, and not a "state" database, the output may be a little bit misleading due to the following effects:
* when the latest `state.apply` was for a subset only, the other states will not be visible
* when corrections have been applied on an individual state with e.g. `state.sls_id`, then this is not included in the information that is shown.

I'm already thinking about an enhancement. currently the output for one minion is the output of the latest `state.apply`/`state.highstate` command that was executed for it. but when we inspect all commands, including `state.sls_id`, etc., starting with the oldest, we can build the actual state for each minion. but it will take much longer to show but then it is more accurate. it can be optimized by not going further back than the most recent full `state.apply`/`state.highstate` command for each minion when it is available.

I'll merge this code in a couple of days. I'm still working on how to reverse-engineer the job's Command(string) and Arguments(object) into a single string that SaltGUI uses. It seems that I wrote that function multiple times, now for the 3rd time. I want to clean that up before the merge.

**Comment by erwindon** [comment]
I used the column title "Tasks".
That was sloppy naming.
Corrected it to "States".

**Comment by erwindon** [comment]
refactored the commandline-constructor; less complicated code and allowing more cases where quotes are not needed

**Comment by erwindon** [comment]
allow navigation from jobid in highstate screen to that job
that was already available in the dropdown menu, but this is easier to use
click on any other part of the row still opens command-box with the original command

**Comment by erwindon** [comment]
fixed issue with 0 jobs returned from the query
the text "(no job)" was only decided upon after handling a job
but that of course does not happen when we start with 0 jobs (of the requested 2 types)

I think this is ready for merge in a few days

**Comment by erwindon** [comment]
merged
