### ISSUE TITLE
There's no OS image for centos stream

### ISSUE THREAD

**Issue by xzenor** [erwindon/SaltGUI#407]
**Describe the bug**
There's no OS image for centos stream

**To Reproduce**
Steps to reproduce the behaviour:
Minions screen, make sure you have a centos stream machine in there and then the logo won't load because it doesn't exist.

**Expected behaviour**
Just copy the original centos logo. It hasn't changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/15305998/143475588-8605ae80-cdec-43b2-92b7-710080f85820.png)

**Additional context**
`cp static/images/os-centos.png static/images/os-centos-stream.png`
Fixed.

**Comment by xzenor** [comment]
this is like... reeeaaaaally low priority but also fairly simple. Would you prefer if I did a pull request for this? I'm not sure which way is easier for you. This stuff I can actually collaborate with if you want :)

**Comment by erwindon** [comment]
pull requests are indeed preferred, as that saves me a little work.
(but always be careful with big surprises such as redesigns or stuff that is not universal enough)
but in this case it was so little work that I just pushed the given change.

and then I searched for a solution when generated urls for images have an error...
so now, when there is a missing icon, it shows a backup icon.
the backup icon even has an html-tooltip to hint on reporting the situation.

please let me know whether the new icon is working.
and then break it by moving a used image out, and see the new warning

**Comment by erwindon** [comment]
rebased branch for #401, announced here because you are involved there as well

**Comment by xzenor** [comment]
Nice solution! 
If I run into another missing icons I'll do a pull request.

**Comment by erwindon** [comment]
fore completeness, the original solution was describe here: https://stackoverflow.com/questions/7995080/html-if-image-is-not-found

the list of icons needed is potentially endless as, in cases like the above, the value for grain `os` is derived from information that the operating system itself provides. I think this was the 3rd request for a new icon after the feature was introduced more than 2 years ago (1st was aws, 2nd was openbsd). looking forward to your first PR!
