### ISSUE TITLE
Add OS icon for Rocky Linux

### ISSUE THREAD

**Issue by byoungstrom** [erwindon/SaltGUI#412]
**Describe the bug**
When viewing the list of minions in the SaltGUI dashboard, any host with OS version 'Rocky 8.4' has a gray triangle icon. The hovertext reports "Unknown OS for image, Please report to the SaltGUI team"

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy a minion on Rocky 8.4
2. Go to http://saltgui:3333/#minions
3. Scroll to the Rocky minion

**Expected behaviour**
An icon from the RockyLinux project in place of the gray triangle

**Screenshots**
![image](https://user-images.githubusercontent.com/7737279/145487973-52619817-12fb-4201-8e0a-a68cd3290145.png)

**Additional context**

**Comment by erwindon** [comment]
A simple icon could quickly be found. It is now added to SaltGUI.
Please let me know whether that addition actually works (as I only simulated that OS).

![os-rocky](https://user-images.githubusercontent.com/3663742/145491234-967d9561-de01-40c1-bb0a-010ce7e08fed.png)

**Comment by byoungstrom** [comment]
Looks good!
