### ISSUE TITLE
Execute "salt-run state.orchestrate ..." with custom pillar data from SaltGUI

### ISSUE THREAD

**Issue by achimmihca** [erwindon/SaltGUI#426]
**Feature request**
I want to execute an [Orchestrate script](https://docs.saltproject.io/en/latest/topics/orchestrate/orchestrate_runner.html) with custom pillar data from SaltGUI.
For example, on command line I can execute the following:
`salt-run state.orchestrate orch.my-orchestrator-script pillar='{"target": "10.32.1.2"}'`

Is it possible to execute this via SaltGUI?

**Describe the solution you'd like**
- SaltGUI's "Manual run" dialog should support `salt-run` statements
    - notably state.orchestrate
- SaltGUI's "Manual run" dialog should support and custom pillar data for the command
    - This would be nice also for normal state.apply. Currently, when I run `state.apply hello pillar='{"bla": "blub"}'` then I get an error message: `Valid double-quoted-string, but followed by text:}'...`
    - Maybe one could add an additional text field to enter custom pillar data JSON string ?

**Describe alternatives you've considered**
Workaround: don't use SaltGUI. Instead run the command from command line.

**Comment by achimmihca** [comment]
I just found #265.
One has to execute `runners.state.orchestrate` in SaltGUI.

The question with the custom pillar data remains.
How can I pass pillar data to a command in SaltGUI?

**Comment by achimmihca** [comment]
> How can I pass pillar data to a command in SaltGUI?

It works when I remove the single quotes. Thus, the following works perfectly fine in SaltGUI:
`runners.state.orchestrate orch.my-orchestrator-script pillar={"target": "10.32.1.2"}`

Sorry for the inconvenience

**Comment by erwindon** [comment]
@achimmihca
The bit of documentation about `runners`/`wheel` prefixes in the command-box was actually added only yesterday!
Previously, it was mentioned only in the `README.md` file.

And indeed, the command-box is not bothered by the syntax that BASH/SH/etc need. Thus the additional quotes are not needed here.
