### ISSUE TITLE
Redirect to original URL parameters after login

### ISSUE THREAD

**Issue by achimmihca** [erwindon/SaltGUI#431]
**Is your feature request related to a problem? Please describe.**
First I want to say thank you!
SaltGUI is a great tool for us in our new configuration management.
Now, we are planning to add links to SaltGUI in notification E-Mails.

There is a little issue though:

- When clicking a link to SaltGUI (e.g. from E-Mail client), then SaltGUI opens with the login screen. This is ok.
    - Example: http://my.salt.com:3333/?id=20220315102657264588#job
- The problem is that after successful login, SaltGUI does not redirect to the clicked link.
    -  Instead, the URL after login is always http://my.salt.com:3333/#minions

**Describe the solution you'd like**
After successful login, SaltGUI should navigate to the URL that was used to open SaltGUI.
Maybe an implementation could look at the original URL parameters (query and fragment) and reapply them after successful login?

**Describe alternatives you've considered**
Current workaround:
- Log in to SaltGUI, then paste the URL of the link in the address bar of the browser, and hit enter.
    - This works because SaltGUI does not open the login screen again for an already logged in browser tab.

**Comment by erwindon** [comment]
approved

**Comment by erwindon** [comment]
The typical implementation for this is that the original url and parameters become parameters of the login screen during the redirect to the login screen.
e.g.:
http://localhost:8000/?id=20220312142559354840#job
(when not logged in) redirects to something like:
http://localhost:8000/?redirect=job&id=20220312142559354840&reason=no-session#login
the parameters are ignored by the actual login procedure (except for `reason`), but they are used to construct the proper target url to go to after finishing the login procedure.

note that there is always the risk that the original page that was specified:
* does not exist
* exists, but has insufficient parameters
* exists, but has wrong parameters
* exists, but does not appear in the list `saltgui_pages` (which fact should remain ignored)

**Comment by achimmihca** [comment]
Sounds good.

However, I have an issue with salt itself: the JID does not seem to be available when runnning a script.
Thus, I cannot create links to SaltGUI.

Anyway, the redirect feature in SaltGUI is still useful when sending/embedding links manually.

**Comment by erwindon** [comment]
See #434 
Can you please review/test the PR?

**Comment by erwindon** [comment]
merged

**Comment by erwindon** [comment]
unmerged
