### ISSUE TITLE
Icon for OpenWRT

### ISSUE THREAD

**Issue by vemilyus** [erwindon/SaltGUI#442]
Hi there, I've attached an icon for the OpenWRT OS for you to add at your convenience.

![os-openwrt](https://user-images.githubusercontent.com/7115009/162611713-52567413-79bb-453b-ae92-cff5808292e5.png)

All the best

**Comment by erwindon** [comment]
I re-scaled the image to 100x100px, just because I'm using that size for all others.

Which exact value is shown in the column "OS version" on the Minions/home page of SaltGUI?
Is that "OpenWRT", or is it different?
The version number is separate information which is not used for the icon filename.

**Comment by vemilyus** [comment]
It's `OpenWrt` + version

**Comment by erwindon** [comment]
@vemilyus
I've added the icon to the source-code on the `master` branch.
Can you try it?

**Comment by vemilyus** [comment]
Works like a charm! Thanks!
