### ISSUE TITLE
Salt-minion version and OS version on gui showing Error and web page is frequently crashing 

### ISSUE THREAD

**Issue by virendrasa** [erwindon/SaltGUI#489]
We have approx 2000+ minions (win+linux) , recently we installed/configured saltGUI but It is not working as expected.
Whenever we trying to access web it hung /crashed and not showing minion and os version details.
Could you help us /suggest any amendment in current config.

CPU: 16
RAM:- 12G
Type :- Virtual Server
OS:- Ubuntu 20.04

>>> salt --versions-report
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.0
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Mar 15 2022, 12:22:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-81-generic
        system: Linux
       version: Ubuntu 20.04 focal

Thanks,
![minion](https://user-images.githubusercontent.com/34012670/202431457-20f12fcd-4ca2-4870-9ba9-bc813275f812.JPG)

**Comment by erwindon** [comment]
Since there is no information that suggests another category, I've marked this as 'question'.

**Comment by virendrasa** [comment]
Hi Erwindon,

Yes , Salt-api is working as well SaltGUI is working .
We are able to login into salgui webpage.

~# systemctl status salt-api
● salt-api.service - The Salt API
     Loaded: loaded (/lib/systemd/system/salt-api.service; disabled; vendor pre>
     Active: active (running) since Thu 2022-11-17 16:56:13 +04; 16h ago
       Docs: man:salt-api(1)
             file:///usr/share/doc/salt/html/contents.html
             https://docs.saltproject.io/en/latest/contents.html
   Main PID: 1865085 (salt-api)
      Tasks: 104 (limit: 14236)
     Memory: 69.7M
     CGroup: /system.slice/salt-api.service
             ├─1865085 /usr/bin/python3 /usr/bin/salt-api
             └─1865100 /usr/bin/python3 /usr/bin/salt-api

>>>>>>>>>>

:~# systemctl status salt-master
● salt-master.service - The Salt Master Server
     Loaded: loaded (/lib/systemd/system/salt-master.service; enabled; vendor p>
     Active: active (running) since Thu 2022-11-17 16:55:48 +04; 17h ago
       Docs: man:salt-master(1)
             file:///usr/share/doc/salt/html/contents.html
             https://docs.saltproject.io/en/latest/contents.html
   Main PID: 1862219 (salt-master)
      Tasks: 178 (limit: 14236)
     Memory: 1.2G
     CGroup: /system.slice/salt-master.service
             ├─1862219 /usr/bin/python3 /usr/bin/salt-master
             ├─1862284 /usr/bin/python3 /usr/bin/salt-master
             ├─1862285 /usr/bin/python3 /usr/bin/salt-master
             ├─1862288 /usr/bin/python3 /usr/bin/salt-master
![salt](https://user-images.githubusercontent.com/34012670/202632145-46b6c672-b8f1-4a68-8cca-4537d7ecc434.JPG)

**Comment by erwindon** [comment]
What happens when you just use 'Wait'?

Please also look at the amount of memory that your browser is using. 2000 minions is a lot of information and a lot of HTML elements to produce in a page. 

The previous maximum I heard of was around 1000.
There is no built-in limit in SaltGUI for the number of minions/tasks/etc; but the amount of information must still be processed.
salt-api returns all information as JSON. it is the task for SaltGUI to transform that into HTML. All that work happens in the browser.

**Comment by erwindon** [comment]
@virendrasa 
there was no response within 2 weeks.
closing the issue as there is not enough useful information to work on
feel free to re-open when more information is made available
