### ISSUE TITLE
highstate summary does not always fit on screen

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#491]
**Describe the bug**
as reported as side-note in #490, the summary with the highstate tasks does not always fit in the available room

**To Reproduce**
Steps to reproduce the behaviour:
1. Run command `state.apply` that applies to many states in the command-box
2. View the output of the same job in the jobs view
3. See error appear in both steps

**Expected behaviour**
All states are visible without overflow effects

**Screenshots**
Screenshots "taken from #490:
![206880987-05471d8d-6299-4514-835c-92179f48705e](https://user-images.githubusercontent.com/3663742/206919988-0e59532c-9395-4134-91d0-13239f78065d.PNG)
![206880985-dd470819-b092-448b-a977-02545bf6c1a6](https://user-images.githubusercontent.com/3663742/206919989-b02bc2a1-d3b0-4844-8bf7-7ef8b672b58c.PNG)

**Comment by erwindon** [comment]
@tazaki
I created a new branch `highstate_summary` for this PR.
I added a bit of CSS styling to the highstate summary visualization to allow line-breaking on any character.
The result is that the line now wraps when it becomes too long.
It works for both the command-box and the job-panel.
There were a several choices for the wrapping style:
1. wrapped lines start at the left-most position (current choice)
2. wrapped lines start at a fixed indentation, this should make the visibility of the minion names
3. wrapped lines start at the same indentation as on the first line, this should make the visibility of the minion names
4. the information starts at the left-most position of the next line when it was too long; the same for each next line
5. the information starts at a fixed indentation of the next line when it was too long; the same for each next line

can you please give this branch a try?
do you think that one of the other styles should have been chosen?

**Comment by erwindon** [comment]
after some testing, I found that the 4 other combinations are actually hard to create:
2+3: that is not something that can be handled with a "span", and it would then become difficult and/or complex;
4+5: this will also move a short list of tasks to the next line, which is then difficult and/or complex to prevent.

**Comment by erwindon** [comment]
added a small fix: we needed an increased line-height to prevent the double-overbars and double-underbars on different lines to touch/overlap. this automatically applies to the tooltip. that was not intended.

**Comment by erwindon** [comment]
note that I regularly "rebase" my development branches, you may need "git pull -r"

**Comment by tazaki** [comment]
Updated the branch to test a bit more with more minions. I think the layout is fine as I agree the other solutions seem more complex without adding anything. I did notice if click the arrows to expand the details of the state results the dots shift a bit. I can't seem to tell where its shifting.

![Capture](https://user-images.githubusercontent.com/899085/207080895-baa9252d-5ab7-4db6-bc19-ebc9676684ef.PNG)
![Capture2](https://user-images.githubusercontent.com/899085/207080898-953546eb-c247-4899-b9d7-7e2eb54fda88.PNG)
In the second screen I clicked the arrow to the right of minion3 to expand the details. You can see the dots above moved over to the right slightly.

**Comment by erwindon** [comment]
merged
@tazaki thx for testing!
