### ISSUE TITLE
401 "Unauthorized" - after Login

### ISSUE THREAD

**Issue by bitchriss** [erwindon/SaltGUI#492]
Hey there,

sadly im struggeling a bit to get the SaltGUI running. Maybe you can help me out?

**Describe the bug**
After successfully login all i see is : {"status":401,"message":"Unauthorized"}

** environment **
Ubuntu 22.04.1 LTS
Python 3.10.6
salt 3005.1
PAM with activedirectory authentication

**Expected behaviour**
I should be able to manage my minions? 

**Screenshots**
![image](https://user-images.githubusercontent.com/64711771/210357938-96747b46-b172-4807-b993-64c29cc5dbdb.png)

**Comment by erwindon** [comment]
for this problem there are 2 possibilities that I can think of:
1. the login actually did not happen
verify by CTRL-CLICK on the 'SaltGUI' logo in the top-left corner
see first few entries 'session_*'
2. the login succeeded, but your login has no actual permissions
verify by CTRL-CLICK on the 'SaltGUI' logo in the top-left corner
see item 'session_perms'

If it is not immediately clear, please paste a screenshot of the 'session_*' options that are visible in step 1 or 2.
(hide at least 50% of the session_token to prevent any session replay by others)

**Comment by bitchriss** [comment]
Hey erwindon,

just to make sure im not totaly stupid i just tried it with an local user and my Domain-Account.. 
i can login with both and have with both the same issue.

pam-auth against salt works:

salt -a pam myserver test.ping
username: salt
password:
myserver:
    True
---
And the screenshot with the session_Params:
![image](https://user-images.githubusercontent.com/64711771/210384917-10910db4-e0e6-4983-ab6c-291c7ec553f9.png)

Many thanks for the help and best regards
Chriss

**Comment by erwindon** [comment]
reading the documentation, I see that this is actually an allowed notation when permissions are arranged per minion.
but '@xxx' permissions should not be granted per minion, as these are master-side permissions.

see https://docs.saltproject.io/en/latest/topics/eauth/index.html:
"The runner/wheel markup is different, since there are no minions to scope the acl to."

**Comment by bitchriss** [comment]
Use my head with a wall. I've removed the hirachy in the permissions and boom minions, jobs, all that beautiful stuff. 

Thank you very much for helping me with that :-)
