### ISSUE TITLE
saltgui_hide_jobs has no effect

### ISSUE THREAD

**Issue by mhagedal** [erwindon/SaltGUI#505]
Hi, I have some noisy jobs I'm trying to suppress using `saltgui_hide_jobs` in my master configuration. It doesn't seem to be working, though.

Following the example from the readme, we can add this to the config:
```yaml
saltgui_hide_jobs:
    - test.ping
```
And sure enough, when I Ctrl+click the SaltGUI logo, the Options page says it is picked up:

![image](https://user-images.githubusercontent.com/130691193/231835914-be940750-4b12-4e8c-9c7c-70916ab14579.png)

However, `test.ping` still appears on the Jobs page and the Recent Jobs pane:

![image](https://user-images.githubusercontent.com/130691193/231838333-54539b70-9f01-4dcb-b6c7-76533e9fa4a8.png)
![image](https://user-images.githubusercontent.com/130691193/231838474-f6b58ad1-7cf9-400d-aa77-c90d9c35a412.png)

It looks like the hidden jobs list is supposed to be stored during login, and then `JobsPanel` assigns it to `_hideJobs` in its constructor:
```js
constructor (pKey) {
  super(pKey);

  // collect the list of hidden/shown functions
  this._showJobs = Utils.getStorageItemList("session", "show_jobs");
  this._hideJobs = Utils.getStorageItemList("session", "hide_jobs");
}
```

I don't think that part is happening, though. When we get to the part of `JobsPanel` that *does* seem to effectively hide jobs, `this._hideJobs` is initially empty instead of being prepopulated with our custom hidden jobs.

![image](https://user-images.githubusercontent.com/130691193/231866979-5e33e78e-331a-4a0b-9829-9cc07c30b4ca.png)

I can ultimately hide my jobs by adding them to the hardcoded values in `_handleRunnerJobsListJobs()`. However, it would be nice to have it work through the master config item instead.

**Comment by erwindon** [comment]
I have recreated your case.
During normal operation, the constructor of class JobsPanel seems to be skipped, leading to the filter not working.
When a page refresh is used, the constructor is properly called and the filter then works as expected.
I'll continue searching for the root-cause...

**Comment by erwindon** [comment]
the mistake is that the constructor is already called when the very first page (the login screen) is shown.
at that time, the needed variables are not retrieved yet.
this also explains why the page-refresh works.
I'll update it to move session related code out of the constructor.

**Comment by erwindon** [comment]
I've tested/committed/pushed the fix.
can you please give it another try?

**Comment by mhagedal** [comment]
That fixed it! Thank you so much for the speedy response and a great project.
