### ISSUE TITLE
salt-api 3006+ needs additional configuration to work

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#510]
**Is your feature request related to a problem? Please describe.**
See https://docs.saltproject.io/en/latest/topics/releases/3006.0.html
Each API subset must now individually be enabled

**Describe the solution you'd like**
Document what to add to the configuration.

**Additional context**
The full list of clients is:
```
netapi_enable_clients:
  - local
  - local_async
  - local_subset
  - runner
  - runner_async
  - ssh
  - wheel
  - wheel_async
```
some are not (yet) needed for SaltGUI

**Comment by erwindon** [comment]
added first warning to documentation

**Comment by erwindon** [comment]
only local, local_async, runner and wheel are needed for SaltGUI

**Comment by cbalan58** [comment]
Hi, just confirming that using only local, local_async, runner and wheel the SaltGUI functionality returned, works fine now.

**Comment by erwindon** [comment]
please re-submit your comment under #511 
I will delete your comment (and this one) when that is done
