### ISSUE TITLE
Salt 3006.0 Fails to Authenticate even with netapi_enable_clients

### ISSUE THREAD

**Issue by Sidicer** [erwindon/SaltGUI#511]
**Describe the bug**
After updating our saltstack to 3006 we were unable to use SaltGUI (mainly we cannot even Authenticate). Saw issue #510 and tried enabling `netapi_enable_clients` with `local, local_async, runner, wheel` in master config to no avail.

Restarted `salt-master`, `salt-minion`, and `salt-api` services on our master server after config changes but still unable to authenticate with SaltGUI

**To Reproduce**
Steps to reproduce the behaviour:
1. Update salt-master to version 3006.0
2. Try to login through Salt-Gui
3. Fail
4. Update `/etc/salt/master` config and add `netapi_enable_clients: -local -local_async -runner -wheel`
5. Restart `salt-master` and `salt-api` services
6. Try to login through salt-gui
7. Fail

**Expected behaviour**
Successful Login

**Screenshots**
![image](https://user-images.githubusercontent.com/9251667/235114097-4e4b118c-1a42-427a-aa4b-df460792c5aa.png)

**Additional context**
Using Yubico as auth

Tried enabling ALL api clients:
```
netapi_enable_clients:
  - local
  - local_async
  - local_subset
  - runner
  - runner_async
  - ssh
  - wheel
  - wheel_async
```
But still fails

**Comment by erwindon** [comment]
#510 is mentionned

**Comment by erwindon** [comment]
@Sidicer 
are you using the release version 2.28.0, or just the latest version?
(I've created #512 to prevent that confusion in the future)
are you able to test this with PAM instead?
I still have my Yubico key, so I should be able to test this.

**Comment by cbalan58** [comment]
Hi, just confirming that using only local, local_async, runner and wheel the SaltGUI functionality returned, works fine now.
I'm using PAM.

**Comment by erwindon** [comment]
it is unlikely that this can be solved in SaltGUI.
but I want to investigate this further and find the root cause.
maybe this can be of benefit to the SaltStack project itself...

**Comment by Sidicer** [comment]
> 

Can confirm that using PAM to login with U/P works with SaltGUI

**Comment by Sidicer** [comment]
If I understand correctly SaltGUI still uses Saltstack/salt-api/Auth backend to authenticate, so 99% chance that the issue i'm facing is with Salt itself and not your SaltGUI ?

**Comment by erwindon** [comment]
yes
from the SaltGUI point of view, the support for the Yubico method (or any other login validation method) is as simple as filling login-parameter 'eauth' with value `yubico` instead of value `pam`.
also, the introduction of `netapi_enable_clients` was a documentation change only for SaltGUI

**Comment by Sidicer** [comment]
Raised [3006.0 breaks Yubico external authentication #64185](https://github.com/saltstack/salt/issues/64185) in Saltstack's Github Issue page, as we both confirmed that the issue is with Salt itself and not your SaltGUI implementation.
Closing this issue currently as there is nothing we can do here.
If you find anything that might help resolve this issue please write here or in the issue mentioned previously! 
Thank you

**Comment by erwindon** [comment]
I'm keeping this open because I want to investigate more.
e.g.:
* what is the actual cause?
* are other `eauth` methods also effected?

I'll anything useful also to https://github.com/saltstack/salt/issues/64185

**Comment by erwindon** [comment]
see my comment in https://github.com/saltstack/salt/issues/64185
I'll leave it at that.

**Comment by erwindon** [comment]
Seems the documentation for e.g. `yubico` needs to be extended with the knowledge of:
* https://github.com/saltstack/salt/blob/3006.x/doc/topics/releases/3006.0.md#how-do-i-migrate-to-the-onedir-packages; and
* https://github.com/saltstack/salt/blob/3006.x/doc/topics/releases/3006.0.md#caveat-of-salt-pip

as explained in https://github.com/saltstack/salt/issues/64185

**Comment by erwindon** [comment]
I've added a few additional lines at the top of the regular documentation.
Originally, that was only about `netapi_enable_clients`, now also `salt-pip` is mentioned, both new developments in 3006.
thx @Sidicer for triggering this!
