### ISSUE TITLE
Cannot authenticate using pam

### ISSUE THREAD

**Issue by jeanbruder** [erwindon/SaltGUI#516]
**Describe the bug**
Once the GUI is deployed and we can connect to, an error appears when trying to connect to using a local account.

Error messages from /var/log/salt/master :
2023-05-25 13:58:12,826 [salt.loaded.int.auth.pam:243 ][ERROR   ][2723155] Error 'auth.pam.python' config value does not exist: /usr/bin/python3
2023-05-25 13:58:13,641 [salt.auth        :313 ][WARNING ][2723155] Authentication failure of type "eauth" occurred.
2023-05-25 13:58:13,641 [salt.master      :2144][WARNING ][2723155] Authentication failure of type "eauth" occurred.

**To Reproduce**
Connect to the GUI with a local user.

**Expected behaviour**
Local created user should be abble to connect to the GUI.

**Screenshots**
![image](https://github.com/erwindon/SaltGUI/assets/72472219/71d48442-b0b4-4392-873a-5561ce4d3fe0)

**Additional context**
N/A

**Comment by erwindon** [comment]
that looks a lot like #514
Since saltstack 3006, setup has become more difficult.
did you follow all the instructions that were issues by the salt project in from https://docs.saltproject.io/en/3006.0/topics/netapi/netapi-enable-clients.html#netapi-enable-clients ?

**Comment by jeanbruder** [comment]
Good morning @erwindon,

When installing SaltGUI, and before reading the thread #514, I applied all the requirements explained in the top section of the SaltGUI pages. I can confirm that my installation of SaltGUI fit all the requirements, including the one from ThasianXi, dealing with my "salt" user belonging to the "root" group (group of the /etc/shadow file on my RHEL 8 server), which seems to me a huge security issue ...

Here's my master configuration file content :
![image](https://github.com/erwindon/SaltGUI/assets/72472219/1a2fb936-91f9-4bdc-93fe-71e8205e6153)

And the output of the recomanded check :
![image](https://github.com/erwindon/SaltGUI/assets/72472219/c98bc2ef-1be1-4ce6-b367-e4fd8aeb7c93)

How can I help on this case ?

Regards,
Jean

**Comment by erwindon** [comment]
sidestep...

> dealing with my "salt" user belonging to the "root" group (group of the /etc/shadow file on my RHEL 8 server), which seems to me a huge security issue ...

in that same line...
it should be avoided to use a generic account (like 'salt') for the saltapi/SaltGUI login.
the fact that software like salt-master/salt-minion/salt-api run as linux user 'salt' does not mean that that is also a loginname for saltapi/SaltGUI. best is to use personal accounts or an access-group (which contains only personal accounts).

**Comment by jeanbruder** [comment]
> sidestep...
> 
> > dealing with my "salt" user belonging to the "root" group (group of the /etc/shadow file on my RHEL 8 server), which seems to me a huge security issue ...
> 
> in that same line... it should be avoided to use a generic account (like 'salt') for the saltapi/SaltGUI login. the fact that software like salt-master/salt-minion/salt-api run as linux user 'salt' does not mean that that is also a loginname for saltapi/SaltGUI. best is to use personal accounts or an access-group (which contains only personal accounts).

@erwindon We plan in the futur to only connect to the GUI using our dedicated ActiveDirectory users, belonging to a specific group.

**Comment by erwindon** [comment]
as you are showing in your screenprint, the issue is with salt-api, not with SaltGUI.
you also show that you followed the relevant steps.
that makes it very hard to provide answers.
I can retry a "RHEL 8" installation locally and let you know my experience with that.

**Comment by jeanbruder** [comment]
@erwindon 
Of courses, as far I did my investigation, You're right that the matter is located on the salt-api side, and not on the SaltGUI side ... New bug report opened : https://github.com/saltstack/salt/issues/64368 Hoping this will help ...

**Comment by erwindon** [comment]
and there is already a suggestion there...
