### ISSUE TITLE
Custom grains dont seem sortable?

### ISSUE THREAD

**Issue by sharkmerry7** [erwindon/SaltGUI#525]
It's me again.

on #grains page 

Custom grains dont seem to allow sorting like the default ones do. is this expected?

Thanks!
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by erwindon** [comment]
> It's me again.

:-)

> Custom grains dont seem to allow sorting like the default ones do

I noticed the same during post-merge testing... and immediately (now a few days ago) fixed it.
see git commit e324e2d438f995b94aee9659ea6ffe200583149c

**Comment by sharkmerry7** [comment]
shameful... i hadnt switched back to master. :(

All is working as expected now. 

Thanks again!!!
