### ISSUE TITLE
Audit Page Requested

### ISSUE THREAD

**Issue by mdtabrezpasha** [erwindon/SaltGUI#528]
**Is your feature request related to a problem? Please describe.**
Feature request for system info  
 
**Describe the solution you'd like**
It would be nice to have a system audit page on the GUI which would give out details like, system make,  model number, serial number, last connected date,  ip and mac address, operating system, and available updates.

**Comment by erwindon** [comment]
technically that seems achievable.
but the main problem would be to make this workable for everyone with just the right types of information shown for all.

let's look at some alternatives first:
* you can try to use the regular Grains page for the overview and just add a bunch of custom columns there using the `saltgui_preview_grains` setting; and
* for available updates, the salt-way is to create states (for `state.apply` or `state.highstate`) that determine the availability of updates. which is the same code as for applying the updates, but running it with `test=true`. The Highstate page should then give a nice overview.

there is a little bit of room for improvements on the Grains page in the `saltgui_preview_grains` facility. the current implementation allows selection of additional grains-info based on either the `grains.get` or the `jsonpath` selection. small additional operations should be possible like combining grains or adding simple highlighting or setting a nicer title.

**Comment by erwindon** [comment]
@mdtabrezpasha your reaction please...

**Comment by mdtabrezpasha** [comment]
Hi Erwin,
              I will try out your solution, but a dedicated page for
systems audit would be awesome, we should be able to select the details we
wish to generate from our systems and download a report.  Your GUI for salt
is  the best available in open source.  keep up the good work.  Thanks for
your support.


Warm Regards,
*Mohammed Tabrez Pasha*
Systems Engineer
SkyNet Systems
Ph:9480126313

**Comment by erwindon** [comment]
currently looking into a HTML report generator.
in the style of [Jinja2](https://en.wikipedia.org/wiki/Jinja_(template_engine)), but much much simpler.

* loop over accepted minions (no selection, no custom ordering)
* fill in value form a named grain

template sample:
```
<html>
<head>
<title>PAGE-TITLE</title>
</head>
<body>
<h1>OVERVIEW</h1>
<table>
<tr>
<th>minion-id</th>
<th>kernelrelease</th>
<th>num_cpus</th>
</tr>
{% for minions %}
<tr>
<td>{{ grain.id }}</td>
<td>{{ grain.kernelrelease }}</td>
<td>{{ grain.num_cpus }}</td>
</tr>
{% endfor %}
</table>
</body>
</html>
```

you mentioned: `details like, system make, model number, serial number, last connected date, ip and mac address, operating system, and available updates`
let's break that down to get the information sources:
* system make --> grain.manufacturer ?
* model number --> which grain?
* serial number --> grain.machine_id?
* last connected date --> how would you determine this?
* ip address --> does not seem to be available, except in the form of a list of addresses
* mac address --> does salt even report this as grain?
* operating system --> grain.osfinger?
* available updates --> that is not available in the grains information, how should this be determined?

before I start any coding, I want to make sure that all information that should go into the overview is actually available in a simple way. can you please update the list of items that you want to report on and on which salt-information that should be based?

**Comment by erwindon** [comment]
@mdtabrezpasha your reaction please?

**Comment by mdtabrezpasha** [comment]
Able to generate the info required using grains.. Thanks Erwin.  you can
close this request.


Warm Regards,
*Mohammed Tabrez Pasha*
Systems Engineer
SkyNet Systems
Ph:9480126313

**Comment by erwindon** [comment]
@mdtabrezpasha 
Mohammed,
Based on you original request, I added a reporting function (page) in a development branch of SaltGUI.
See https://github.com/erwindon/SaltGUI/tree/zzz-reports
The page can generate reports in HTML based on user-provided templates.
Repeating sections can be added based on either minions or keys.
For minions, selected grains/pillar-data can be filled in.
For keys, the key-status and/or fingerprint can be filled in.
The documentation provides the technical details.
Do you like to review this function?

**Comment by Bearbobs** [comment]
It works as expected, only that command pallete icon is still visible on the report pdf/print

**Comment by Bearbobs** [comment]
<img width="448" alt="image" src="https://github.com/erwindon/SaltGUI/assets/21145870/7fabbfdd-0ef7-4a27-bece-79b7c86b88be">
Yeah sure, it seems scalable 
but i was  thinking of hacking a data saving layer in db like psql  or exporting csv as using the data will be lot easier from there

**Comment by erwindon** [comment]
@Bearbobs 
I was able to make a few more improvements on the ability to print screens:
* hide the close-button of the command-box
* hide the help-button of the command-box
* hide the "Run command" button of the command-box
* hide the text "waiting for (more) events" in the status-line of the Events page
* hide the text "press [button] to [continue/begin/pause]" in the status-line of some pages

but I was not able to reproduce your screen-print...
earlier (less that 1 hour ago), I was assuming the screen-print was a print of the command-box.
on closer inspection, I see that this is a "Report".
my guess is that you have put those elements in the report template itself?
can you place the report template in this issue?

**Comment by erwindon** [comment]
note: since all of the "hiding" is done using passive css code, it may help to just do a full refresh of your browser (usually SHIFT-F5)

**Comment by Bearbobs** [comment]
Let me test and get back to you

**Comment by erwindon** [comment]
any results?

**Comment by Bearbobs** [comment]
Still there, didn't see any change
Steps to reproduce:
Command/ctrl + p -> export as pdf

**Comment by erwindon** [comment]
I must be looking in the wrong place...
* did you do a `git pull -r` ?
* did you do a full refresh in the browser while in saltgui (shift-F5) ?
* which browser is used (brand+version) ?
* which operating system is used (brand+version) ?
* does the effect occur in the print-preview or only in the resulting pdf ?
* which saltgui page are you printing (url, hostname-part not needed) ?
* if the page is a "report", can you please upload the html file for that ?

**Comment by Bearbobs** [comment]
Hey, 
I tested the changes on chrome mac and yes also tried refreshing cache

**Comment by erwindon** [comment]
@Bearbobs 
you more-or-less answered the first 4 questions (with the assumption that you have an up-to-date git workspace, a recent browser version and a recent operating system version).
still your edition seems to show something visually different than mine.

so I must zoom in more to explain the differences:
- does the effect occur in the print-preview or only in the resulting pdf ?
- which saltgui page are you printing (url, hostname-part not needed) ?
- if the page is a "report", can you please upload the html file for that ?

**Comment by Bearbobs** [comment]
* effect occurs in both
* I am printing report page
* No, i can't share that

**Comment by erwindon** [comment]
another question...
the reporting facility was a proposal based on the original request in this github issue.
since it was not used so far, I moved it to "experimental" status.
it seems that you are using it, which is good.
would you like this reporting-faciity to be added to the main branch?

**Comment by Bearbobs** [comment]
It can be part of the main branch if such a use case is required by others as well.

I will get back to you on that as i did modify the code base a lot to tailor to my need

**Comment by erwindon** [comment]
> [...] as i did modify the code base a lot to tailor to my need
anything that would benefit other SaltGUI users?
