### ISSUE TITLE
Gui issue on startup

### ISSUE THREAD

**Issue by mdtabrezpasha** [erwindon/SaltGUI#529]
**Describe the bug**
Gui Not Loading up

**To Reproduce**
Did a fresh install of Salt, configured everthing including the GUI.. page is no loading as expected.
![image](https://github.com/erwindon/SaltGUI/assets/50145580/42b550a7-1bc7-4b4f-b052-6145880ecae3)

![image](https://github.com/erwindon/SaltGUI/assets/50145580/cf8e1d6a-913e-48e4-8963-0a81b2739c5c)

**Expected behaviour**
login page expected

**Additional context**
Its a fresh install. i have tried doing it on another server. same isue.

**Comment by erwindon** [comment]
@mdtabrezpasha 
can you please look at the console output?
you seem to be using Firefox: CTRL+SHIFT+K to open that.
the information there should provide more insight in what is going on...

**Comment by mdtabrezpasha** [comment]
Hi Erwin,
              I did CTRL+SHIFT+K , got the below output.. is this a
configuration issue on my side? What am I doing wrong?  This is my 18th
installation this year.. never had this issue before.

[image: image.png]


Warm Regards,
*Mohammed Tabrez Pasha*
Systems Engineer
SkyNet Systems
Ph:9480126313

**Comment by mdtabrezpasha** [comment]
on Chrome browser
![image](https://github.com/erwindon/SaltGUI/assets/50145580/32bea519-a368-4cb9-9628-9ef6dad97671)

**Comment by erwindon** [comment]
the initial content that you see is from file `index.html`, so basic setup of `rest_cherrypy` is ok, and the `app` entry in the `rest_cherrypy` block is also ok.

but all other files are found using the entries `static` and `static_path`, please check both.
I get the same effect when value for `static` is not correct... (must be `/static`)
I get the same effect when value for `static_path` is not correct... (must be full path to `.../SaltGUI/saltgui/static`)

the directory `static` and everything below should be readable for user `salt` (which is the user-id used by salt-api).
I get the same effect when that the files are not readable or when the directories are not readable+executable...

hope this helps...

**Comment by mdtabrezpasha** [comment]
you were right.. static folder setting was the problem.  the path in the master file was wrong.. Thank's a lot of helping brother.   you can close this issue.  Thanks again.
