### ISSUE TITLE
Cache minion data to store grains data  and last online status for offline minions

### ISSUE THREAD

**Issue by Bearbobs** [erwindon/SaltGUI#538]
**Is your feature request related to a problem? Please describe.**
It's hard to analyze the infra if the minions are offline so having a cache layer will be helpful to save the data till the minion is offline

**Describe the solution you'd like**
Having a cache connection with a database to save the status of offline minions

**Comment by Bearbobs** [comment]
without persistent storage it will be pointless I guess as the browser storage will still be dependent on the minion's last online status for that browser.
The workflow which I thought of looks like this:
1.) A backend agent to ping salt-master on schedule to save all minion info in a database
2.) API from this agent to serve cache mode data on saltgui and a toggle to switch between cache and live mode.
I will keep you posted for upstream contribution

**Comment by erwindon** [comment]
@mbgevers looks promising. can you please open a new issue for this? just repeat the question there. if I copy your question, then I become the owner instead of you.... let's have all further discussion in the new issue.
