### ISSUE TITLE
Build tool documentation

### ISSUE THREAD

**Issue by ebaklund** [erwindon/SaltGUI#559]
**Problem**
SaltGUI does not necessarily build due to node.js incompatibles.
Neither does `runtests.sh` necessarily work out-of-the-box.

**Requirement**
As a first time user of SaltGUI ,attempting to build it,
i would like to have in the documentation an updated list of build tools, with precise tool  versions, 
in order know what tools to install and make SaltGUI build and test on **first attempt**.

**Comments**
`runtests.sh` could possibly also be started with a verification of that the right version of build tools are installed.
The build tools are currently documented as:
```
You'll need at least:
docker-compose 1.12 or above
nodejs 8.11 or above
yarn 1.7 or above
```
that seems too imprecise.

Also, `package-lock.json `is missing. That file can be a drag during development but is valuable for client users who just want build to work.

**Comment by erwindon** [comment]
@ebaklund 
There is no procedure to build SaltGUI, only procedures for test and development scenarios.
But I'll try to update/improve that anyway.
I have no time for this in this week. But it should be possible after that...

**Comment by erwindon** [comment]
actions:
* better show that `runtests` is a bash script

**Comment by erwindon** [comment]
> `You'll need at least...`
> that seems too imprecise.

can you please elaborate on that?

**Comment by erwindon** [comment]
ping?

**Comment by erwindon** [comment]
@ebaklund 
I did not receive additional information.
feel free to request additional changes in a new issue.
