### ISSUE TITLE
Logo for Fedora Asahi Remix

### ISSUE THREAD

**Issue by vemilyus** [erwindon/SaltGUI#602]
Hi there,

I found a new missing logo :wink: : `os-fedora-asahi-remix.png`.

Feel free to add it at your convenience :) The original logos are [here](https://github.com/AsahiLinux/artwork/tree/main/logos).

Thanks, and all the best,
Alex

**Comment by erwindon** [comment]
https://raw.githubusercontent.com/AsahiLinux/artwork/main/logos/png_512/AsahiLinux_logomark.png

**Comment by erwindon** [comment]
I pushed the new image, but scaled to 100x100 and renamed.
obviously I simulated this OS, so that was only a partial test.
please let me know whether it works for you.

**Comment by vemilyus** [comment]
You are a machine! It works. I always pull master for my setup and refreshed while doing other maintenance and there it was :D 

Thanks bunches!

**Comment by erwindon** [comment]
I happened to be online and you provided all the needed details --> easy!
