### ISSUE TITLE
howto docker pull / run SaltGui

### ISSUE THREAD

**Issue by luchermans** [erwindon/SaltGUI#62]
I have installed [docker](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04) and successfully docker run hello-world.
How do I run the [SaltGui docker](https://github.com/maerteijn/SaltGUI/tree/master/docker)?

**Comment by maerteijn** [comment]
Well, its [documented](https://github.com/maerteijn/SaltGUI#development-environment-with-docker) right?

**Comment by luchermans** [comment]
Sorry didn't see that.  Installed docker-composer and runned the up
but I get http://localhost:3333/    404 Not Found   The path '/app' was not found.

**Comment by maerteijn** [comment]
I don't know. Did you checkout the repository, then `cd docker` and `docker-compose up`? There you also see a lot of output what gives a hint?

**Comment by erwindon** [comment]
@luchermans : ping

**Comment by erwindon** [comment]
no response from requestor, closing
