### ISSUE TITLE
Auth Failure of type "token" for one account, other works just fine. 

### ISSUE THREAD

**Issue by theLadyStardust** [erwindon/SaltGUI#638]
**Describe the bug**
When logged into the web interface, minion, key, and job elements display as "(error)" 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install saltgui and salt-api
2. Create a user on the salt host using useradd [user] and passwd [user]
3. Add user to saltgui accounts in `/etc/salt/master`

> external_auth:
>    pam:
>         root:
>             - .*
>             - '@runner'
>             - '@wheel'
>             - '@jobs'
>         user:
>             - .*
>             - '@runner'
>             - '@wheel'
>             - '@jobs'

4. Login to web UI
5. Minions show up as (error), display 401 perms issue when hovered over. 
![image](https://github.com/user-attachments/assets/ad8604b9-59a9-48a9-a1ce-d677ffa9f8f9)

The weird thing is that all the session perms show up fine when I ctrl+click the logo in the top-left. 
![image](https://github.com/user-attachments/assets/45a2fd6f-c81f-4abe-a22c-3cdc2fe9090b)
And when I curl into the interface? 

> 
> curl -v -d eauth=pam -d username=user -d password=passwd http://saltguiip:3333/login/
> ...
> {"return": [{"token": "[token hash]", "expire": 1729137861.8588834, "start": 1729094661.858883, "user": "user", "eauth": "pam", "perms": [".*", "@jobs", "@runner", "@wheel"]}]}

Weird thing #2: I have another account, root, which works just fine when I log in.  I can see and manage jobs and minions fine. 

`tail /var/logs/salt/master` gives a bunch of entries like this one: 
> 2024-10-16 16:00:17,058 [salt.master      :2432][WARNING ][85045] Authentication failure of type "token" occurred.

Which makes me thing it's an issue with how I set up the account? But I can log in just fine, and it gives me the permissions.

**Comment by erwindon** [comment]
This is a category of questions that I can barely help with...
A lot is working. The permissions look the same as here. One account is working.
But there is a difference between the accounts.
Did you follow https://docs.saltproject.io/en/3006.0/topics/netapi/netapi-enable-clients.html ?
Did you follow section "Quick start using PAM as authentication method" in the SaltGUI manual ?

**Comment by theLadyStardust** [comment]
It was something stupid - I had only restarted the salt-api service, not salt-master. Thanks for the prompt response!
