### ISSUE TITLE
Fully-featured docker image for production?

### ISSUE THREAD

**Issue by ZsBT** [erwindon/SaltGUI#644]
It is rather a question/discussion.

I'm using your GUI for about two years, thanks a lot for the work. However, I used to build my own alpine-based docker image. 

What do you think about an 'example' folder which is not for development purpose but almost a ready-to-use instance? Also, a version of public docker image could be useful where everything is included, so the end-user just needs to drop the salt auth config to the master.d directory.

Of course I'm willing to discuss in details and contribute to this stuff if you are interested in this.

**Comment by erwindon** [comment]
@ZsBT
That may look like a great idea.
The most 'difficult' part of SaltGUI is actually setting op salt-api using the /etc/salt/master file. How can a container-image help with that? because that overlaps with the regular salt-api installation...
I don't mind contributions in this area, but they have to be usable for a broad range of users.

So:
* you will have to contribute this in the form of a PR
* I can guide you to make this usable for a broad public
* that also means that the work has to be incremental, so minimal effort is lost when I cannot accept that step of the PR

**Comment by erwindon** [comment]
@ZsBT  ping...

**Comment by ZsBT** [comment]
Sorry I missed the previous notification.  I'm glad to work on this.
My idea for the master config is to place the salt-api related settings under a separate file in the /etc/salt/master.d folder. This is how I use it for my project.
Before the first PR, I'd like to agree on the approach how a universal image would serve most of the users. Some of my ideas:

- use supervisord to serve both salt-master and salt-api
- proper health check for both services
- execution of custom startup scripts, e.g. executable files mounted in /docker-init.d

Also, what linux distro do you prefer for the base image? My personal favorites are Alpine, then Debian. However, the recent chaos with Broadcom migration made Alpine packages messy, so I guess we should start with Debian.

What source should we use for Salt? OS packages from the distro repo, or obtaining the latest/stable release from the Salt project?

These are my first thoughts, I might have missed some other important aspects.

**Comment by erwindon** [comment]
The more I think of this...
I feel that what you are proposing is not actually part of SaltGUI as it will also contain image(builder)s for SaltStack components.
You are then actually creating a product-integration-bundle of which SaltGUI is just one component.
That would best be done in a new github project, which is owned by you, and which pulls SaltStack and SaltGUI and maybe other software as well.
That gives you all the freedom to set that up and to make choices.
I would be happy to make practical changes to SaltGUI to make the integration easier, when you identify them.

**Comment by ZsBT** [comment]
Indeed, maybe I have over-complicated the plan. So the full-stack image will be in a dedicated project that will integrate services from different sources.
I think SaltGUI is already in good shape for an easy integration, a git submodule made it simple to implement.

Thanks for helping me to find a nice way for the next steps, I'm closing this issue as there's nothing to do in this project.

**Comment by erwindon** [comment]
@ZsBT good luck with your project!
