### ISSUE TITLE
404 on missing files in /static

### ISSUE THREAD

**Issue by plakun** [erwindon/SaltGUI#653]
**Describe the bug**
When loading a SaltGUI page, the browser tries to load pages from the static folder, which by default do not exist:
minion.txt
salt-motd.txt
salt-motd.html
salt-auth.txt
These files are optional and if i didnt create them they still tries to be downloaded through page loading.
That leads to big amount of 404 responses on load-balancer ahead of Salt, which triggers alerting. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open dev console in browser
2. Load SaltGUI web page

**Expected behaviour**
If there are no files in the static directory, there should be no attempt to load them

**Comment by plakun** [comment]
With empty files everything is ok
![изображение](https://github.com/user-attachments/assets/090b01b1-05ac-4a02-8a13-bf72c7d62f94)

**Comment by erwindon** [comment]
I actually did not have the opportunity to verify it myself. That is now planned for this weekend. And I will then update the documentation with this information.

**Comment by erwindon** [comment]
`minions.txt` --> empty file is already explicitly treated same as absent file, see `Panel.js`, documentation mentions empty file is possible --> OK
`salt-motd.txt` --> empty file is already explicitly treated same as absent file, see `Login.js`, added explicit note in documentation about use of empty file. --> OK
`salt-motd.html` --> empty file is already explicitly treated same as absent file, see `Login.js`, added explicit note in documentation about use of empty file. --> OK
`salt-auth.txt` --> empty file is already explicitly treated same as absent file, see `Login.js``, added explicit note in documentation about use of empty file. --> OK
so there should indeed be no side effects from placing empty files.

added a line to each of the 3 relevant sections of the documentation.
