### ISSUE TITLE
Issue Regarding SatlGUI authentication

### ISSUE THREAD

**Issue by bijeshgit-cloud** [erwindon/SaltGUI#659]
Hello Erwin Dondorp,

How are you? Hope you are well !!

I am encountering an authentication failure in SaltGUI while using the PAM authentication method with SaltStack. The specific user (bijesh) is being rejected by the authentication process when attempting to execute commands using the salt command-line interface with the -a pam authentication flag or even on web interface as well.

The issue was identified during testing of authentication against the Salt Master using the SaltGUI interface, as well as with direct salt CLI commands. The error logs show that SaltStack is unable to authenticate the user using the configured PAM authentication method, which results in the following errors:

```
2024-12-06 10:04:15,244 [salt.utils.lazy  :98  ][DEBUG   ][143331] LazyLoaded pam.auth
2024-12-06 10:04:16,821 [salt.loaded.int.auth.pam:244 ][ERROR   ][143331] Pam auth failed for bijesh:  
2024-12-06 10:04:16,822 [salt.auth        :313 ][WARNING ][143331] Authentication failure of type "eauth" occurred.
2024-12-06 10:04:16,823 [salt.master      :2153][WARNING ][143331] Authentication failure of type "eauth" occurred.
```
The error points to a failure with the eauth mechanism, which is expected to work with PAM-based authentication, but fails when tested.

**Configuration Files Involved**

The following configuration files have been reviewed:

1. /etc/salt/master: The configuration has external_auth set for PAM, and the user saltuser is authorized with the @wheel role. However, no file authentication method was specified in some of the tests, which is mentioned in the error logs.
```
auth.pam.service: login
authentication:
  pam:
    enabled: True
    # Optional: Define which PAM service to use (e.g., 'login', 'sshd', etc.)
    service: login
#
#
# The external auth system uses the Salt auth modules to authenticate and
# validate users to access areas of the Salt system.
external_auth:
  pam:    
    bijesh:
      - .*
      - '@runner'
      - 'jobs.*' 
      - '@wheel'
      - '@jobs'
```
2. /etc/pam.d/salt : 

Example content for /etc/pam.d/salt (for verification):
```
#%PAM-1.0
auth required pam_unix.so
account required pam_unix.so
password required pam_unix.so
session required pam_unix.so
```
This ensures that SaltStack leverages standard UNIX password authentication for PAM.

**Logs from Salt Master**

The authentication failure errors recorded in the logs point to a failure in PAM authentication for the user saltuser1. Below are the relevant log excerpts:
```
2024-12-06 10:04:15,244 [salt.utils.lazy  :98  ][DEBUG   ][143331] LazyLoaded pam.auth
2024-12-06 10:04:16,821 [salt.loaded.int.auth.pam:244 ][ERROR   ][143331] Pam auth failed for bijesh:  
2024-12-06 10:04:16,822 [salt.auth        :313 ][WARNING ][143331] Authentication failure of type "eauth" occurred.
2024-12-06 10:04:16,823 [salt.master      :2153][WARNING ][143331] Authentication failure of type "eauth" occurred.
```
Details from the logs:

PAM Auth Failure: The error message Pam auth failed for bijesh: indicates that SaltStack was unable to authenticate the user bijesh via PAM.
eauth Failure: The log entries from salt.auth and salt.master confirm that the eauth method failed to authenticate the user, leading to the failure of any command execution via SaltStack.
General Warning: The warning messages from salt.master and salt.auth suggest that Salt’s external authentication mechanism is incorrectly configured or not functioning as expected.

Miscellaneous Command outputs:

```
# salt --version
salt 3006.9 (Sulfur)

# salt -a pam web\* test.version
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 192.168.xx.xx
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] The functions from module 'pam' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded pam.auth
username: bijesh
password: 
[DEBUG   ] Closing AsyncReqChannel instance
[DEBUG   ] Closing IPCMessageSubscriber instance
[DEBUG   ] The functions from module 'nested' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded nested.output
Authentication error occurred.

# pamtester sudo bijesh authenticate
Password: 
pamtester: successfully authenticated

# grep bijesh /etc/passwd
bijesh:x:1002:1003::/home/bijesh:/bin/bash

# grep bijesh /etc/shadow
bijesh:$6$rounds=100000$/on3FsAsHFwsPnez$LobB2469GQoIhtMQNlQk97eLm/UEGUJPnA9FJXawuHpZXi3Qr/Wxi25P5Vi5A0IRnL17JA5DhEmJZIqUDNKgz/:20062:0:99999:7:::

# id bijesh
uid=1002(bijesh) gid=1003(bijesh) groups=1003(bijesh),10(wheel)
```

**Comment by erwindon** [comment]
Since the error also occurs with the plain `salt` command, this does not seem to be a problem with SaltGUI.

The documentation for SaltGUI has these 2 remarks:
* To successfully use `salt-api` with a default PAM setup, if may be needed to grant read access on `/etc/shadow` to the `salt` user. This is best done using `sudo usermod --append --groups shadow salt`.
* Restart everything with `pkill salt-master && pkill salt-api && salt-master -d && salt-api -d`

did you follow these instructions?
