### ISSUE TITLE
session timeout broken since merge of api-cleanup-error-handling

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#67]
Since #64 , the session timeout detector stopped working on page navigation and page refresh.
Function `isAuthenticated` uses an api call `/login` without parameters (what happened to `/stats`?). On a timed-out session, this returns (200=OK + "please login") with a fresh sessionid cookie. SaltGUI then happily continues and all further API calls return (401=Unauthorized), instead of returning to the login page.

**Comment by maerteijn** [comment]
I'll adjusted this  to `/stats` and committed it in 9df7ac44b9e35522db5bf66026bdb5c33b72b59b

**Comment by erwindon** [comment]
There is indeed a 401 now. Previously that one was detected and a redirect to `/login` followed. That still does not happen any more. That behaviour was what triggered this report.

**Comment by maerteijn** [comment]
Page refresh should be working now, as `isAuthenticated` is called in the `constructor` or `Router`:
https://github.com/maerteijn/SaltGUI/blob/master/saltgui/static/scripts/router.js#L15

So we need to call it as well when switching routes. I'll think of it tomorrow (and see if I can add a test for it)

**Comment by erwindon** [comment]
retested. confirmed that on session timeout a redirect to the login screen occurs again
