### ISSUE TITLE
Use javascript modules

### ISSUE THREAD

**Issue by maerteijn** [erwindon/SaltGUI#72]
I came across this article: https://developers.google.com/web/fundamentals/primers/modules
Could be something useful for SaltGUI (instead of `window.x` hacks to define global functions)
Specifically:
* utils.js:
`window.elapsedToString = function(date) {`
* utils.js:
`window.createElement = function(type, className, content) {`
* utils.js:
`window.escape = function(input) {`
* utils.js:
`window.makeTargetText = function(targetType, targetPattern) {`
* parsecmdline.js:
`window.parseCommandLine = function(toRun, args, params) {`

**Comment by smarletta** [comment]
I would recommend to use a Webpack based build. And then do the modularization. On my fork I am almost done. If you want I will do a PR when ready.

**Comment by erwindon** [comment]
@smarletta 
So far we have minimized the number of frameworks that are used.
I will review your fork this weekend and comment on it.
thx for your involvement!

**Comment by smarletta** [comment]
@erwindon My stuff is not ready yet, will create PR when ready. I would webpack not name a framework. But it depends on the perspective.

**Comment by erwindon** [comment]
See also #183

**Comment by erwindon** [comment]
@smarletta after which or your PRs can this issue be considered fully done?

**Comment by smarletta** [comment]
Hi,

When the import and export stuff is in.

Erwin Dondorp <notifications@github.com> schrieb am So., 10. März 2019,
13:32:

**Comment by erwindon** [comment]
@smarletta so that would be number PR 192, isn't it?

**Comment by smarletta** [comment]
I guess 194 was the number

Erwin Dondorp <notifications@github.com> schrieb am So., 10. März 2019,
13:57:

**Comment by erwindon** [comment]
I actually meant to say 194 :blush:
