### ISSUE TITLE
compatability with tornado?

### ISSUE THREAD

**Issue by raddessi** [erwindon/SaltGUI#84]
Is it possible to run this while using rest_tornado? Would I have to spin up a separate cherrypy server? how hard would it be to integrate if not already? Thanks!

**Comment by erwindon** [comment]
It looks like rest_tornado supports only the API calls.
While rest_cherrypy supports both API calls and content.
And the latter is where SaltGUI gets its html/css/js from.
So rest_tornado alone does not seem to be enough for SaltGUI.

No separate server is needed. Each of rest_cherrypy and rest_tornado become an instance of salt-api.
There is only one start command: {{systemctl start salt-api}}
So, just adding the rest_cherrypy configuration-block should be enough.

**Comment by raddessi** [comment]
I'm already using the rest_tornado though and I recall there were reasons for switching from cherrypy I just don't know what they were. I tried running both and it wasn't happy. Is content serving only thing required from cherrypy here? If so I can just put the html dir behind nginx or any other server.

**Comment by erwindon** [comment]
Feel free to experiment with that setup, but we cannot support it due to its higher complexity. Feel free to ask for enhancements and/or provide PRs to get your setup working better.
