### ISSUE TITLE
UX accepting minion keys

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#98]
I think that user experience with accepting minion key could be even better if we could except minion keys exactly directly picking option `Accept key`
<img width="922" alt="zrzut ekranu 2018-12-26 o 20 35 38" src="https://user-images.githubusercontent.com/5910851/50455446-4cacc180-094e-11e9-89cb-9d037a792bac.png">

and just show output of this commend instead of asking users to execute commend 2nd time with new window
<img width="1266" alt="zrzut ekranu 2018-12-26 o 20 35 53" src="https://user-images.githubusercontent.com/5910851/50455480-8251aa80-094e-11e9-8da5-fb5e13d9c36d.png">

**Comment by dawidmalina** [comment]
The same story should be applied to delete key and reject key.

**Comment by erwindon** [comment]
@dawidmalina 
I used to have a prototype that had all 3 steps (open box, run command, close box) in one action. i.e. the command box was bypassed completely. I found that it was too difficult to predict whether commands would be successful and abandoned that again. Your solution is actually a bit of both and does not have that problem.
I'll try this one out and let us both test it.

**Comment by erwindon** [comment]
Looked at this and found no reasonable solution, i.e. one that does not include additional/confusing extra gui elements. 
Feel free to re-open (but preferably new issue) with a complete proposal. But please describe the solution first before setting up a PR.
