### ISSUE TITLE
UX grains information

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#99]
I think that user experience with displaying grains information could be even better if we could format output instead printing raw array, map
<img width="917" alt="zrzut ekranu 2018-12-26 o 20 55 41" src="https://user-images.githubusercontent.com/5910851/50455850-f0976c80-0950-11e9-91c7-c025f3d5f579.png">

**Comment by dawidmalina** [comment]
For example instead:
```
[
  "nbd3",
  "nbd15",
  "nbd1",
  "nbd13",
  "nbd8",
  "nbd11",
  "nbd6",
  "nbd4",
  "nbd2",
  "nbd14",
  "nbd0",
  "nbd9",
  "nbd12",
  "nbd7",
  "nbd10",
  "nbd5"
]
```
have
```
- "nbd3"
- "nbd15"
- "nbd1"
- "nbd13"
- "nbd8"
- "nbd11"
- "nbd6"
- "nbd4"
- "nbd2"
- "nbd14"
- "nbd0"
- "nbd9"
- "nbd12"
- "nbd7"
- "nbd10"
- "nbd5"
```

**Comment by erwindon** [comment]
@dawidmalina 
The Salt API is handling JSON data. Therefore SaltGUI is also using JSON data. This can be compared to the use of commandline option `--out=json` on the `salt` commandline, Indeed the `salt` command has a YAML output, unless specified otherwise.
The first layer of data is an object with the data per grain. That object is taken apart to get the presentation as it is now. There is no further interpretation on the grain details.
I fail to see a generic solution on your request here, but additional suggestions are welcome.

**Comment by dawidmalina** [comment]
I know this is raw json but this exactly the same story as with state output (at the beginning we had was raw json, right?) which now is pretty formatted output. And with the the pillars or grains we usually can end up with object of type: string, list, map (last two can nest more object but also with the same type). So what I had in mind was quite simple formatter which will detect one of this types.

**Comment by dawidmalina** [comment]
Maybe this library can be used: https://www.npmjs.com/package/json-to-pretty-yaml

**Comment by erwindon** [comment]
I'm not worried/afraid of the actual code needed to create such presentation data.

I did not realize that the `salt` command-line is actually taking JSON parameters and producing YAML output. So there should be less reason to fear similar behaviour in SaltGUI. I'll create a prototype.

**Comment by dawidmalina** [comment]
I've just found the smaller js library https://github.com/jeffsu/json2yaml and the output is quite  satisfactory with very small modification in the codebase:
- grains
<img width="486" alt="zrzut ekranu 2018-12-29 o 15 14 52" src="https://user-images.githubusercontent.com/5910851/50539198-9f6bc080-0b7c-11e9-9997-2927f5d06c69.png">


- pillar
<img width="373" alt="zrzut ekranu 2018-12-29 o 15 15 05" src="https://user-images.githubusercontent.com/5910851/50539194-95e25880-0b7c-11e9-810a-5f2b4835b3c0.png">

**Comment by erwindon** [comment]
This issues is continued as PR #127 (this issues will be closed in a few days)
